//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.Utilities.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GrowIndigo.Utilities.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Grow Indigo.
        /// </summary>
        public static string GrowOnline_Common_AboutGrowINd {
            get {
                return ResourceManager.GetString("GrowOnline_Common_AboutGrowINd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agricultural sustainability is a looming question as climate change is creating more uncertainty
        ///                    around the weather. The soil resource is central to agriculture and therefore sustainable agriculture is
        ///                    inherently dependent on soil health. Providing solutions that will help to sustain in the future is a driver for GrowIndigo offering biological and digital solutions to empower farmers to have relevant information and also improve soil health..
        /// </summary>
        public static string GrowOnline_Common_AboutGrowINdTitle1 {
            get {
                return ResourceManager.GetString("GrowOnline_Common_AboutGrowINdTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grow Indigo is a joint initiative of Mahyco Grow and Indigo Ag established in 2017. Combining the
        ///                    technological innovation of the two market leaders we will help maximize farmers&apos; benefits. Our primary
        ///                    objective is to tackle the challenges farmers face every day and assist them to improve their yields,
        ///                    generate more revenue and implement sustainable farming practices..
        /// </summary>
        public static string GrowOnline_Common_AboutGrowINdTitle2 {
            get {
                return ResourceManager.GetString("GrowOnline_Common_AboutGrowINdTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is the earliest agri-innovation corporate in India, founded on a vision to bring modern science to resolve
        ///                    farming
        ///                    challenges, with a view to improve farmers welfare and the nutritional security of the country. Mahyco Grow™
        ///                    has
        ///                    pioneered several agri innovations including many crop hybrids for the first time in India. Its Seed
        ///                    Innovation
        ///                    vertical has expanded to Africa and South East [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GrowOnline_Common_AboutGrowINdTitle3 {
            get {
                return ResourceManager.GetString("GrowOnline_Common_AboutGrowINdTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to improves grower profitability, environmental sustainability, and consumer health through
        ///                    the
        ///                    use of natural microbiology and digital technologies. The company&apos;s scientific discoveries and digital
        ///                    innovations
        ///                    create new value from soil to sale, benefiting tens of thousands of growers across millions of acres.
        ///                    Working
        ///                    across the supply chain, Indigo is furthering its mission of harness [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GrowOnline_Common_AboutGrowINdTitle4 {
            get {
                return ResourceManager.GetString("GrowOnline_Common_AboutGrowINdTitle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string GrowOnline_Common_AboutUs {
            get {
                return ResourceManager.GetString("GrowOnline_Common_AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string GrowOnline_Common_Address {
            get {
                return ResourceManager.GetString("GrowOnline_Common_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Home.
        /// </summary>
        public static string GrowOnline_Common_Backtohome {
            get {
                return ResourceManager.GetString("GrowOnline_Common_Backtohome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Price.
        /// </summary>
        public static string GrowOnline_Common_BestPrice {
            get {
                return ResourceManager.GetString("GrowOnline_Common_BestPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biological Treatment.
        /// </summary>
        public static string GrowOnline_Common_BiologicalTreatment {
            get {
                return ResourceManager.GetString("GrowOnline_Common_BiologicalTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Now.
        /// </summary>
        public static string GrowOnline_Common_BuyNow {
            get {
                return ResourceManager.GetString("GrowOnline_Common_BuyNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart Details.
        /// </summary>
        public static string GrowOnline_Common_CartDetail {
            get {
                return ResourceManager.GetString("GrowOnline_Common_CartDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CATEGORIES.
        /// </summary>
        public static string GrowOnline_Common_Cat {
            get {
                return ResourceManager.GetString("GrowOnline_Common_Cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        public static string GrowOnline_Common_ChangeLanguage {
            get {
                return ResourceManager.GetString("GrowOnline_Common_ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        public static string GrowOnline_Common_CheckOut {
            get {
                return ResourceManager.GetString("GrowOnline_Common_CheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout Detail.
        /// </summary>
        public static string GrowOnline_Common_CheckoutDetails {
            get {
                return ResourceManager.GetString("GrowOnline_Common_CheckoutDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change State.
        /// </summary>
        public static string GrowOnline_Common_ChnageState {
            get {
                return ResourceManager.GetString("GrowOnline_Common_ChnageState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string GrowOnline_Common_City {
            get {
                return ResourceManager.GetString("GrowOnline_Common_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string GrowOnline_Common_Close {
            get {
                return ResourceManager.GetString("GrowOnline_Common_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string GrowOnline_Common_Companyname {
            get {
                return ResourceManager.GetString("GrowOnline_Common_Companyname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Product.
        /// </summary>
        public static string GrowOnline_Common_CompanyProduct {
            get {
                return ResourceManager.GetString("GrowOnline_Common_CompanyProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string GrowOnline_Common_ContactUs {
            get {
                return ResourceManager.GetString("GrowOnline_Common_ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue shopping.
        /// </summary>
        public static string GrowOnline_Common_continueShop {
            get {
                return ResourceManager.GetString("GrowOnline_Common_continueShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account!.
        /// </summary>
        public static string GrowOnline_Common_CreateAccount {
            get {
                return ResourceManager.GetString("GrowOnline_Common_CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop.
        /// </summary>
        public static string GrowOnline_Common_Crop {
            get {
                return ResourceManager.GetString("GrowOnline_Common_Crop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop Category.
        /// </summary>
        public static string GrowOnline_Common_CropCategory {
            get {
                return ResourceManager.GetString("GrowOnline_Common_CropCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop Type.
        /// </summary>
        public static string GrowOnline_Common_CropType {
            get {
                return ResourceManager.GetString("GrowOnline_Common_CropType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop Priority.
        /// </summary>
        public static string GrowOnline_Common_CrpPriority {
            get {
                return ResourceManager.GetString("GrowOnline_Common_CrpPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSTN  Number.
        /// </summary>
        public static string GrowOnline_Common_cstn_Number {
            get {
                return ResourceManager.GetString("GrowOnline_Common_cstn_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Quantity.
        /// </summary>
        public static string GrowOnline_Common_CurrentQuantity {
            get {
                return ResourceManager.GetString("GrowOnline_Common_CurrentQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        public static string GrowOnline_Common_Daqte {
            get {
                return ResourceManager.GetString("GrowOnline_Common_Daqte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string GrowOnline_Common_Description {
            get {
                return ResourceManager.GetString("GrowOnline_Common_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        public static string GrowOnline_Common_District {
            get {
                return ResourceManager.GetString("GrowOnline_Common_District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string GrowOnline_Common_DOB {
            get {
                return ResourceManager.GetString("GrowOnline_Common_DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string GrowOnline_Common_Email {
            get {
                return ResourceManager.GetString("GrowOnline_Common_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Id&apos;s.
        /// </summary>
        public static string GrowOnline_Common_EmailIds {
            get {
                return ResourceManager.GetString("GrowOnline_Common_EmailIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while removing product from cart..
        /// </summary>
        public static string GrowOnline_Common_ErrorProductRemoved {
            get {
                return ResourceManager.GetString("GrowOnline_Common_ErrorProductRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Delivery.
        /// </summary>
        public static string GrowOnline_Common_FastDeli {
            get {
                return ResourceManager.GetString("GrowOnline_Common_FastDeli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Within minimum defined days.
        /// </summary>
        public static string GrowOnline_Common_FastDeliWith30 {
            get {
                return ResourceManager.GetString("GrowOnline_Common_FastDeliWith30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string GrowOnline_Common_Feedback {
            get {
                return ResourceManager.GetString("GrowOnline_Common_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firm Name.
        /// </summary>
        public static string GrowOnline_Common_FirmName {
            get {
                return ResourceManager.GetString("GrowOnline_Common_FirmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string GrowOnline_Common_Free {
            get {
                return ResourceManager.GetString("GrowOnline_Common_Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GST  Percentage.
        /// </summary>
        public static string GrowOnline_Common_gst {
            get {
                return ResourceManager.GetString("GrowOnline_Common_gst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GST Number.
        /// </summary>
        public static string GrowOnline_Common_gst_number {
            get {
                return ResourceManager.GetString("GrowOnline_Common_gst_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GST Percent.
        /// </summary>
        public static string GrowOnline_Common_GstPercentage {
            get {
                return ResourceManager.GetString("GrowOnline_Common_GstPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guaranteed price.
        /// </summary>
        public static string GrowOnline_Common_GuranteeBestPrice {
            get {
                return ResourceManager.GetString("GrowOnline_Common_GuranteeBestPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string GrowOnline_Common_Home {
            get {
                return ResourceManager.GetString("GrowOnline_Common_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House No..
        /// </summary>
        public static string GrowOnline_Common_houseNo {
            get {
                return ResourceManager.GetString("GrowOnline_Common_houseNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMEI Number.
        /// </summary>
        public static string GrowOnline_Common_imeiNumber {
            get {
                return ResourceManager.GetString("GrowOnline_Common_imeiNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Code.
        /// </summary>
        public static string GrowOnline_Common_ItemCode {
            get {
                return ResourceManager.GetString("GrowOnline_Common_ItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License number.
        /// </summary>
        public static string GrowOnline_Common_license_no {
            get {
                return ResourceManager.GetString("GrowOnline_Common_license_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string GrowOnline_Common_Login {
            get {
                return ResourceManager.GetString("GrowOnline_Common_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string GrowOnline_Common_Logout {
            get {
                return ResourceManager.GetString("GrowOnline_Common_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Quantity to Book.
        /// </summary>
        public static string GrowOnline_Common_maxQuan {
            get {
                return ResourceManager.GetString("GrowOnline_Common_maxQuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Quantity to Book.
        /// </summary>
        public static string GrowOnline_Common_MaxQuantity {
            get {
                return ResourceManager.GetString("GrowOnline_Common_MaxQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Quantity to Book.
        /// </summary>
        public static string GrowOnline_Common_minQuan {
            get {
                return ResourceManager.GetString("GrowOnline_Common_minQuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Quantity to Book.
        /// </summary>
        public static string GrowOnline_Common_MinQuantity {
            get {
                return ResourceManager.GetString("GrowOnline_Common_MinQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        public static string GrowOnline_Common_MobileNumber {
            get {
                return ResourceManager.GetString("GrowOnline_Common_MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        public static string GrowOnline_Common_MyAccount {
            get {
                return ResourceManager.GetString("GrowOnline_Common_MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Orders.
        /// </summary>
        public static string GrowOnline_Common_MyOrders {
            get {
                return ResourceManager.GetString("GrowOnline_Common_MyOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string GrowOnline_Common_MyProfile {
            get {
                return ResourceManager.GetString("GrowOnline_Common_MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME.
        /// </summary>
        public static string GrowOnline_Common_Name {
            get {
                return ResourceManager.GetString("GrowOnline_Common_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no product in cart.
        /// </summary>
        public static string GrowOnline_Common_noCartProduct {
            get {
                return ResourceManager.GetString("GrowOnline_Common_noCartProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order History.
        /// </summary>
        public static string GrowOnline_Common_Orderhistory {
            get {
                return ResourceManager.GetString("GrowOnline_Common_Orderhistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Online.
        /// </summary>
        public static string GrowOnline_Common_OrderOnline {
            get {
                return ResourceManager.GetString("GrowOnline_Common_OrderOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders over 1000k.
        /// </summary>
        public static string GrowOnline_Common_OrderOVer {
            get {
                return ResourceManager.GetString("GrowOnline_Common_OrderOVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing Size.
        /// </summary>
        public static string GrowOnline_Common_PackingSize {
            get {
                return ResourceManager.GetString("GrowOnline_Common_PackingSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing Size.
        /// </summary>
        public static string GrowOnline_Common_PackSize {
            get {
                return ResourceManager.GetString("GrowOnline_Common_PackSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan Number.
        /// </summary>
        public static string GrowOnline_Common_PanNumber {
            get {
                return ResourceManager.GetString("GrowOnline_Common_PanNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Complete.
        /// </summary>
        public static string GrowOnline_Common_PayComp {
            get {
                return ResourceManager.GetString("GrowOnline_Common_PayComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Detail.
        /// </summary>
        public static string GrowOnline_Common_PayDetail {
            get {
                return ResourceManager.GetString("GrowOnline_Common_PayDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a payment option to purchase the products.
        /// </summary>
        public static string GrowOnline_Common_PayDetail1 {
            get {
                return ResourceManager.GetString("GrowOnline_Common_PayDetail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pincode.
        /// </summary>
        public static string GrowOnline_Common_Pincode {
            get {
                return ResourceManager.GetString("GrowOnline_Common_Pincode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select.
        /// </summary>
        public static string GrowOnline_Common_PleaseSelect {
            get {
                return ResourceManager.GetString("GrowOnline_Common_PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string GrowOnline_Common_pRICAVYpOLICY {
            get {
                return ResourceManager.GetString("GrowOnline_Common_pRICAVYpOLICY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string GrowOnline_Common_Price {
            get {
                return ResourceManager.GetString("GrowOnline_Common_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Details.
        /// </summary>
        public static string GrowOnline_Common_PrimaryDetails {
            get {
                return ResourceManager.GetString("GrowOnline_Common_PrimaryDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Categories List.
        /// </summary>
        public static string GrowOnline_Common_ProCat {
            get {
                return ResourceManager.GetString("GrowOnline_Common_ProCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRODUCT.
        /// </summary>
        public static string GrowOnline_Common_Product {
            get {
                return ResourceManager.GetString("GrowOnline_Common_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Listing.
        /// </summary>
        public static string GrowOnline_Common_Product_CatDetails {
            get {
                return ResourceManager.GetString("GrowOnline_Common_Product_CatDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product list.
        /// </summary>
        public static string GrowOnline_Common_ProductCat {
            get {
                return ResourceManager.GetString("GrowOnline_Common_ProductCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Company Name.
        /// </summary>
        public static string GrowOnline_Common_productComName {
            get {
                return ResourceManager.GetString("GrowOnline_Common_productComName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Detail.
        /// </summary>
        public static string GrowOnline_Common_ProductDetail {
            get {
                return ResourceManager.GetString("GrowOnline_Common_ProductDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Id.
        /// </summary>
        public static string GrowOnline_Common_ProductId {
            get {
                return ResourceManager.GetString("GrowOnline_Common_ProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string GrowOnline_Common_ProductName {
            get {
                return ResourceManager.GetString("GrowOnline_Common_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product is removed from cart successfully..
        /// </summary>
        public static string GrowOnline_Common_ProductRemoved {
            get {
                return ResourceManager.GetString("GrowOnline_Common_ProductRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUANTITY.
        /// </summary>
        public static string GrowOnline_Common_Quantity {
            get {
                return ResourceManager.GetString("GrowOnline_Common_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Shop.
        /// </summary>
        public static string GrowOnline_Common_QuickShop {
            get {
                return ResourceManager.GetString("GrowOnline_Common_QuickShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read More.
        /// </summary>
        public static string GrowOnline_Common_ReadMore {
            get {
                return ResourceManager.GetString("GrowOnline_Common_ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver Name.
        /// </summary>
        public static string GrowOnline_Common_ReceiverName {
            get {
                return ResourceManager.GetString("GrowOnline_Common_ReceiverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string GrowOnline_Common_Register {
            get {
                return ResourceManager.GetString("GrowOnline_Common_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retailer FirstName.
        /// </summary>
        public static string GrowOnline_Common_RetailerFirstName {
            get {
                return ResourceManager.GetString("GrowOnline_Common_RetailerFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retailer LastName.
        /// </summary>
        public static string GrowOnline_Common_RetailerLastName {
            get {
                return ResourceManager.GetString("GrowOnline_Common_RetailerLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and continue.
        /// </summary>
        public static string GrowOnline_Common_SaveandCont {
            get {
                return ResourceManager.GetString("GrowOnline_Common_SaveandCont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Products Here......
        /// </summary>
        public static string GrowOnline_Common_SearchProduct {
            get {
                return ResourceManager.GetString("GrowOnline_Common_SearchProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Payment.
        /// </summary>
        public static string GrowOnline_Common_SecurePay {
            get {
                return ResourceManager.GetString("GrowOnline_Common_SecurePay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100% secure payment.
        /// </summary>
        public static string GrowOnline_Common_SecurePayMessage {
            get {
                return ResourceManager.GetString("GrowOnline_Common_SecurePayMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seed License Validity.
        /// </summary>
        public static string GrowOnline_Common_SeedLicenceValidity {
            get {
                return ResourceManager.GetString("GrowOnline_Common_SeedLicenceValidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop per Crop.
        /// </summary>
        public static string GrowOnline_Common_sEEDSsUBcAT {
            get {
                return ResourceManager.GetString("GrowOnline_Common_sEEDSsUBcAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select State.
        /// </summary>
        public static string GrowOnline_Common_SelectState {
            get {
                return ResourceManager.GetString("GrowOnline_Common_SelectState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sellers List.
        /// </summary>
        public static string GrowOnline_Common_SellerList {
            get {
                return ResourceManager.GetString("GrowOnline_Common_SellerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping.
        /// </summary>
        public static string GrowOnline_Common_Shipping {
            get {
                return ResourceManager.GetString("GrowOnline_Common_Shipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Address.
        /// </summary>
        public static string GrowOnline_Common_ShippingAddress {
            get {
                return ResourceManager.GetString("GrowOnline_Common_ShippingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By:.
        /// </summary>
        public static string GrowOnline_Common_SortBy {
            get {
                return ResourceManager.GetString("GrowOnline_Common_SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string GrowOnline_Common_State {
            get {
                return ResourceManager.GetString("GrowOnline_Common_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string GrowOnline_Common_Status {
            get {
                return ResourceManager.GetString("GrowOnline_Common_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Line 1.
        /// </summary>
        public static string GrowOnline_Common_Streetline1 {
            get {
                return ResourceManager.GetString("GrowOnline_Common_Streetline1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Line 2.
        /// </summary>
        public static string GrowOnline_Common_Streetline12 {
            get {
                return ResourceManager.GetString("GrowOnline_Common_Streetline12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string GrowOnline_Common_SubInfo {
            get {
                return ResourceManager.GetString("GrowOnline_Common_SubInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        public static string GrowOnline_Common_SubTotal {
            get {
                return ResourceManager.GetString("GrowOnline_Common_SubTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taluka.
        /// </summary>
        public static string GrowOnline_Common_Taluka {
            get {
                return ResourceManager.GetString("GrowOnline_Common_Taluka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        public static string GrowOnline_Common_Tax {
            get {
                return ResourceManager.GetString("GrowOnline_Common_Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term of use.
        /// </summary>
        public static string GrowOnline_Common_Termofuse {
            get {
                return ResourceManager.GetString("GrowOnline_Common_Termofuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Conditions.
        /// </summary>
        public static string GrowOnline_Common_TermSANDcONDITIONS {
            get {
                return ResourceManager.GetString("GrowOnline_Common_TermSANDcONDITIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string GrowOnline_Common_Total {
            get {
                return ResourceManager.GetString("GrowOnline_Common_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town.
        /// </summary>
        public static string GrowOnline_Common_Town {
            get {
                return ResourceManager.GetString("GrowOnline_Common_Town", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string GrowOnline_Common_User {
            get {
                return ResourceManager.GetString("GrowOnline_Common_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Company.
        /// </summary>
        public static string GrowOnline_Common_UserCompany {
            get {
                return ResourceManager.GetString("GrowOnline_Common_UserCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vat Number.
        /// </summary>
        public static string GrowOnline_Common_vatNumber {
            get {
                return ResourceManager.GetString("GrowOnline_Common_vatNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Cart.
        /// </summary>
        public static string GrowOnline_Common_ViewCart {
            get {
                return ResourceManager.GetString("GrowOnline_Common_ViewCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500 Internal Server Error.
        /// </summary>
        public static string GrowOnline_Message_500InternalServer {
            get {
                return ResourceManager.GetString("GrowOnline_Message_500InternalServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Grow Indigo.
        /// </summary>
        public static string GrowOnline_Message_AboutUsHeading {
            get {
                return ResourceManager.GetString("GrowOnline_Message_AboutUsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agricultural sustainability is a looming question as climate change is creating more
        ///                            uncertainty around the weather. The soil resource is central to agriculture and therefore sustainable
        ///                            agriculture is inherently dependent on soil health..
        /// </summary>
        public static string GrowOnline_Message_AboutUsHeadingTextbox {
            get {
                return ResourceManager.GetString("GrowOnline_Message_AboutUsHeadingTextbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agricultural sustainability is a looming question as climate change is creating more uncertainty
        ///                            around the weather. The soil resource is central to agriculture and therefore sustainable agriculture
        ///                            is inherently dependent on soil health..
        /// </summary>
        public static string GrowOnline_Message_AboutUsHeadingTextbox2 {
            get {
                return ResourceManager.GetString("GrowOnline_Message_AboutUsHeadingTextbox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Term of Use.
        /// </summary>
        public static string GrowOnline_Message_acceptTerm {
            get {
                return ResourceManager.GetString("GrowOnline_Message_acceptTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Terms and Privacy Policy.
        /// </summary>
        public static string GrowOnline_Message_AcceptTerms {
            get {
                return ResourceManager.GetString("GrowOnline_Message_AcceptTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addrees has been saved successfully..
        /// </summary>
        public static string GrowOnline_Message_AddAddress {
            get {
                return ResourceManager.GetString("GrowOnline_Message_AddAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Address field is required..
        /// </summary>
        public static string GrowOnline_Message_Address {
            get {
                return ResourceManager.GetString("GrowOnline_Message_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CART TOTALS.
        /// </summary>
        public static string GrowOnline_Message_CartDetail {
            get {
                return ResourceManager.GetString("GrowOnline_Message_CartDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for submitting your query. Our Team member will contact you as soon as possible.
        /// </summary>
        public static string GrowOnline_Message_CiontactUs {
            get {
                return ResourceManager.GetString("GrowOnline_Message_CiontactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The City filed is required..
        /// </summary>
        public static string GrowOnline_Message_CityReq {
            get {
                return ResourceManager.GetString("GrowOnline_Message_CityReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got Question? Call Us.
        /// </summary>
        public static string GrowOnline_Message_ContactUs {
            get {
                return ResourceManager.GetString("GrowOnline_Message_ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CSTN  Number field is required..
        /// </summary>
        public static string GrowOnline_Message_cstn_Number {
            get {
                return ResourceManager.GetString("GrowOnline_Message_cstn_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Current Quantity field is required..
        /// </summary>
        public static string GrowOnline_Message_CurrentQuality {
            get {
                return ResourceManager.GetString("GrowOnline_Message_CurrentQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Description field is required..
        /// </summary>
        public static string GrowOnline_Message_Description {
            get {
                return ResourceManager.GetString("GrowOnline_Message_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The District field is required..
        /// </summary>
        public static string GrowOnline_Message_District {
            get {
                return ResourceManager.GetString("GrowOnline_Message_District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Date of Birth field is required..
        /// </summary>
        public static string GrowOnline_Message_DOB {
            get {
                return ResourceManager.GetString("GrowOnline_Message_DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email Address filed is required..
        /// </summary>
        public static string GrowOnline_Message_Email {
            get {
                return ResourceManager.GetString("GrowOnline_Message_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is not in correct format..
        /// </summary>
        public static string GrowOnline_Message_EmailCorrectFormat {
            get {
                return ResourceManager.GetString("GrowOnline_Message_EmailCorrectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter OTP.
        /// </summary>
        public static string GrowOnline_Message_Enterotp {
            get {
                return ResourceManager.GetString("GrowOnline_Message_Enterotp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Phone number.
        /// </summary>
        public static string GrowOnline_Message_EnterPhoneNumber {
            get {
                return ResourceManager.GetString("GrowOnline_Message_EnterPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving addrees..
        /// </summary>
        public static string GrowOnline_Message_ErrorAddAddress {
            get {
                return ResourceManager.GetString("GrowOnline_Message_ErrorAddAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while adding Product in cart.
        /// </summary>
        public static string GrowOnline_Message_ErrorProductAdded {
            get {
                return ResourceManager.GetString("GrowOnline_Message_ErrorProductAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retreive state .Please try again!.
        /// </summary>
        public static string GrowOnline_Message_ErrorSaveandCont {
            get {
                return ResourceManager.GetString("GrowOnline_Message_ErrorSaveandCont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while updating the entries.
        /// </summary>
        public static string GrowOnline_Message_ErrorUserProfileUpdate {
            get {
                return ResourceManager.GetString("GrowOnline_Message_ErrorUserProfileUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Firm Name field is required..
        /// </summary>
        public static string GrowOnline_Message_FirmNameReq {
            get {
                return ResourceManager.GetString("GrowOnline_Message_FirmNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is a joint initiative of Mahyco Grow and Indigo Ag established in
        ///                                2017.
        ///                                Combining the technological innovation of the two market leaders we will help maximize farmers&apos;
        ///                                benefits. Our primary objective is to tackle the challenges farmers face every day and assist them to
        ///                                improve their yields..
        /// </summary>
        public static string GrowOnline_Message_Footer1 {
            get {
                return ResourceManager.GetString("GrowOnline_Message_Footer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GST Number filed is required..
        /// </summary>
        public static string GrowOnline_Message_gst_number {
            get {
                return ResourceManager.GetString("GrowOnline_Message_gst_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The House Number field is required..
        /// </summary>
        public static string GrowOnline_Message_houseNo {
            get {
                return ResourceManager.GetString("GrowOnline_Message_houseNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House No..
        /// </summary>
        public static string GrowOnline_Message_HouseNoReq {
            get {
                return ResourceManager.GetString("GrowOnline_Message_HouseNoReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TheHouse No. is required.
        /// </summary>
        public static string GrowOnline_Message_HouseNoRequired {
            get {
                return ResourceManager.GetString("GrowOnline_Message_HouseNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IMEI Number filed is required..
        /// </summary>
        public static string GrowOnline_Message_imeiNumber {
            get {
                return ResourceManager.GetString("GrowOnline_Message_imeiNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Item Code field is required..
        /// </summary>
        public static string GrowOnline_Message_ItemCodeReq {
            get {
                return ResourceManager.GetString("GrowOnline_Message_ItemCodeReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Mobile Number is not registered with us . Please Register with your mobile number and try again..
        /// </summary>
        public static string GrowOnline_Message_LgnMobilecheck {
            get {
                return ResourceManager.GetString("GrowOnline_Message_LgnMobilecheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The License number field is required..
        /// </summary>
        public static string GrowOnline_Message_license_no {
            get {
                return ResourceManager.GetString("GrowOnline_Message_license_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while registration.
        /// </summary>
        public static string GrowOnline_Message_LoginFailed {
            get {
                return ResourceManager.GetString("GrowOnline_Message_LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Mobile Number already exists ..
        /// </summary>
        public static string GrowOnline_Message_MobileNumberAlreadyExits {
            get {
                return ResourceManager.GetString("GrowOnline_Message_MobileNumberAlreadyExits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Mobile Number field should be of 9 numeric digits..
        /// </summary>
        public static string GrowOnline_Message_MobileNumberCorrectFormat {
            get {
                return ResourceManager.GetString("GrowOnline_Message_MobileNumberCorrectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Mobile Number field is required..
        /// </summary>
        public static string GrowOnline_Message_MobileNumberReq {
            get {
                return ResourceManager.GetString("GrowOnline_Message_MobileNumberReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Product Added for Now.
        /// </summary>
        public static string GrowOnline_Message_NoProduct {
            get {
                return ResourceManager.GetString("GrowOnline_Message_NoProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Products Available for now.
        /// </summary>
        public static string GrowOnline_Message_NoProductAvai {
            get {
                return ResourceManager.GetString("GrowOnline_Message_NoProductAvai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Sub-Products Available for now.
        /// </summary>
        public static string GrowOnline_Message_NoSubCatProductAvai {
            get {
                return ResourceManager.GetString("GrowOnline_Message_NoSubCatProductAvai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opps. There was an error, please try again later..
        /// </summary>
        public static string GrowOnline_Message_Oops {
            get {
                return ResourceManager.GetString("GrowOnline_Message_Oops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server encountered an internal server error and was unable to complete your request..
        /// </summary>
        public static string GrowOnline_Message_Oops1 {
            get {
                return ResourceManager.GetString("GrowOnline_Message_Oops1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OTP field should be of 4 numeric digits..
        /// </summary>
        public static string GrowOnline_Message_OTPCorrectFormat {
            get {
                return ResourceManager.GetString("GrowOnline_Message_OTPCorrectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OTP is incorrect.
        /// </summary>
        public static string GrowOnline_Message_OTPNotfound {
            get {
                return ResourceManager.GetString("GrowOnline_Message_OTPNotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OTP  field is required..
        /// </summary>
        public static string GrowOnline_Message_OtpRequired {
            get {
                return ResourceManager.GetString("GrowOnline_Message_OtpRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will send you OTP..
        /// </summary>
        public static string GrowOnline_Message_otpSend {
            get {
                return ResourceManager.GetString("GrowOnline_Message_otpSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Pan Number field is required..
        /// </summary>
        public static string GrowOnline_Message_PanNumber {
            get {
                return ResourceManager.GetString("GrowOnline_Message_PanNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your transfer.
        /// </summary>
        public static string GrowOnline_Message_PayComp {
            get {
                return ResourceManager.GetString("GrowOnline_Message_PayComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Pincode field is required..
        /// </summary>
        public static string GrowOnline_Message_Pincode {
            get {
                return ResourceManager.GetString("GrowOnline_Message_Pincode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Price field is required..
        /// </summary>
        public static string GrowOnline_Message_Price {
            get {
                return ResourceManager.GetString("GrowOnline_Message_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product added in cart successfull..
        /// </summary>
        public static string GrowOnline_Message_ProducAdded {
            get {
                return ResourceManager.GetString("GrowOnline_Message_ProducAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This product is already added in cart..
        /// </summary>
        public static string GrowOnline_Message_ProductAdded {
            get {
                return ResourceManager.GetString("GrowOnline_Message_ProductAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Id.
        /// </summary>
        public static string GrowOnline_Message_ProductIDReq {
            get {
                return ResourceManager.GetString("GrowOnline_Message_ProductIDReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Product Name filed is required..
        /// </summary>
        public static string GrowOnline_Message_ProductName {
            get {
                return ResourceManager.GetString("GrowOnline_Message_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product is removed from cart successfully..
        /// </summary>
        public static string GrowOnline_Message_ProductRemove {
            get {
                return ResourceManager.GetString("GrowOnline_Message_ProductRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Receiver Name field is required..
        /// </summary>
        public static string GrowOnline_Message_ReceiverNameREq {
            get {
                return ResourceManager.GetString("GrowOnline_Message_ReceiverNameREq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulation, your account has been successfullty created. Please Login to sign in.
        /// </summary>
        public static string GrowOnline_Message_RegistrationSuccess {
            get {
                return ResourceManager.GetString("GrowOnline_Message_RegistrationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Retailer FirstName filed is required..
        /// </summary>
        public static string GrowOnline_Message_RetailerFirstName {
            get {
                return ResourceManager.GetString("GrowOnline_Message_RetailerFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retailer First Name cannot be longer than 150 characters..
        /// </summary>
        public static string GrowOnline_Message_RetailerFirstNameMaxLength {
            get {
                return ResourceManager.GetString("GrowOnline_Message_RetailerFirstNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Retailer LastName filed is required..
        /// </summary>
        public static string GrowOnline_Message_RetailerLastName {
            get {
                return ResourceManager.GetString("GrowOnline_Message_RetailerLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retailer Last Name cannot be longer than 150 characters..
        /// </summary>
        public static string GrowOnline_Message_RetailerLastNameMaxLength {
            get {
                return ResourceManager.GetString("GrowOnline_Message_RetailerLastNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products will be displayed according to your respective selected state!.
        /// </summary>
        public static string GrowOnline_Message_SaveandCont {
            get {
                return ResourceManager.GetString("GrowOnline_Message_SaveandCont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Seed License Validity filed is required.
        /// </summary>
        public static string GrowOnline_Message_SeedLicenceValidity {
            get {
                return ResourceManager.GetString("GrowOnline_Message_SeedLicenceValidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Shipping Address field is required..
        /// </summary>
        public static string GrowOnline_Message_ShippingAddressREq {
            get {
                return ResourceManager.GetString("GrowOnline_Message_ShippingAddressREq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The State field is required..
        /// </summary>
        public static string GrowOnline_Message_State {
            get {
                return ResourceManager.GetString("GrowOnline_Message_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Street Line 1 filed is required..
        /// </summary>
        public static string GrowOnline_Message_Streetline1 {
            get {
                return ResourceManager.GetString("GrowOnline_Message_Streetline1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Line 1.
        /// </summary>
        public static string GrowOnline_Message_StreetLine1Display {
            get {
                return ResourceManager.GetString("GrowOnline_Message_StreetLine1Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Street Line 2 filed is required..
        /// </summary>
        public static string GrowOnline_Message_Streetline2 {
            get {
                return ResourceManager.GetString("GrowOnline_Message_Streetline2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Line 2.
        /// </summary>
        public static string GrowOnline_Message_Streetline2Display {
            get {
                return ResourceManager.GetString("GrowOnline_Message_Streetline2Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Taluka field is required..
        /// </summary>
        public static string GrowOnline_Message_Taluka {
            get {
                return ResourceManager.GetString("GrowOnline_Message_Taluka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Conditions.
        /// </summary>
        public static string GrowOnline_Message_TermsC {
            get {
                return ResourceManager.GetString("GrowOnline_Message_TermsC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agree to our terms of use.
        /// </summary>
        public static string GrowOnline_Message_TermsCLogin {
            get {
                return ResourceManager.GetString("GrowOnline_Message_TermsCLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Town field is required..
        /// </summary>
        public static string GrowOnline_Message_Town {
            get {
                return ResourceManager.GetString("GrowOnline_Message_Town", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Update your Profile to continue to cart.
        /// </summary>
        public static string GrowOnline_Message_UpdateCartProfile {
            get {
                return ResourceManager.GetString("GrowOnline_Message_UpdateCartProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The User Company field is required..
        /// </summary>
        public static string GrowOnline_Message_UserCompany {
            get {
                return ResourceManager.GetString("GrowOnline_Message_UserCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile Updated successfully..
        /// </summary>
        public static string GrowOnline_Message_UserProfileUpdate {
            get {
                return ResourceManager.GetString("GrowOnline_Message_UserProfileUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Vat Number field is required..
        /// </summary>
        public static string GrowOnline_Message_vatNumber {
            get {
                return ResourceManager.GetString("GrowOnline_Message_vatNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while removing product from cart..
        /// </summary>
        public static string GrowOnline_MessageError_ProductRemove {
            get {
                return ResourceManager.GetString("GrowOnline_MessageError_ProductRemove", resourceCulture);
            }
        }
    }
}
