//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area_loss
    {
        public string Cntr_code { get; set; }
        public string prd_year { get; set; }
        public string prd_season { get; set; }
        public string prd_code { get; set; }
        public float issue_area { get; set; }
        public float Pld_loss { get; set; }
        public float Area_Rej { get; set; }
        public float nrarea_loss { get; set; }
        public float Sown_area { get; set; }
        public float Exist_area { get; set; }
        public float Recd_area { get; set; }
        public float Notrecd_area { get; set; }
        public string Field1 { get; set; }
        public string Field2 { get; set; }
    }
}
