//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public int TrId { get; set; }
        public string UserId { get; set; }
        public string IPAddress { get; set; }
        public string ActionType { get; set; }
        public string ModuleName { get; set; }
        public System.DateTime TrDate { get; set; }
    }
}
