//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Center_target
    {
        public string Cntr_code { get; set; }
        public string Prd_year { get; set; }
        public string Prd_season { get; set; }
        public string Prd_code { get; set; }
        public byte trg_ver { get; set; }
        public Nullable<byte> Cntr_rank { get; set; }
        public Nullable<double> Trg_qty { get; set; }
        public Nullable<float> Trg_area { get; set; }
        public Nullable<float> rej_per { get; set; }
        public Nullable<float> Pro_per { get; set; }
        public Nullable<float> Del_per { get; set; }
        public Nullable<float> Gin_Per { get; set; }
        public Nullable<float> Raw_per { get; set; }
        public Nullable<float> Pld_per { get; set; }
        public Nullable<float> rej_area { get; set; }
        public Nullable<float> nrarea_loss { get; set; }
        public Nullable<float> prd_imp { get; set; }
        public Nullable<double> req_qty { get; set; }
        public Nullable<float> req_area { get; set; }
        public Nullable<float> expct_prodty { get; set; }
        public Nullable<float> add_area { get; set; }
        public string prd_Dummy { get; set; }
        public string Eval_code { get; set; }
        public string Eval_FYrSn { get; set; }
        public string Eval_SYrSn { get; set; }
        public string Eval_TYrSn { get; set; }
        public string Prodty_FYrSn { get; set; }
        public string Prodty_SYrSn { get; set; }
        public string Prodty_TYrSn { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> ent_date { get; set; }
        public string user_name { get; set; }
        public Nullable<byte> bom_flag { get; set; }
        public Nullable<byte> req_flag { get; set; }
        public Nullable<byte> upd_flag { get; set; }
        public Nullable<System.DateTime> erp_date { get; set; }
        public string erp_reqno { get; set; }
        public string erp_msg { get; set; }
    }
}
