//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Centre_Master
    {
        public string cntr_code { get; set; }
        public string cntr_Desc { get; set; }
        public string Reg_code { get; set; }
        public string Reg_Desc { get; set; }
        public string stat_code { get; set; }
        public string Cntr_abbr { get; set; }
        public string Zone { get; set; }
        public string Zone_Desc { get; set; }
        public string Comapany { get; set; }
        public string CompanyCode { get; set; }
    }
}
