//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMRtwently
    {
        public string cntrcode { get; set; }
        public string prd_year { get; set; }
        public string prd_season { get; set; }
        public string prd_code { get; set; }
        public string ppmsID { get; set; }
        public string PLDstatus { get; set; }
        public string grCode { get; set; }
        public string Hyconfirm { get; set; }
        public string isolation { get; set; }
        public Nullable<double> isoDistance { get; set; }
        public Nullable<int> totFplant { get; set; }
        public Nullable<int> totMplant { get; set; }
        public Nullable<double> existarea { get; set; }
        public Nullable<double> PldArea { get; set; }
        public string PldReason { get; set; }
        public Nullable<int> Roughcount { get; set; }
        public string Roughtype { get; set; }
        public Nullable<int> MRoughcount { get; set; }
        public string MRoughtype { get; set; }
        public string Landmark { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> DateVisit { get; set; }
        public string obr_Recomd { get; set; }
        public string ExpYield { get; set; }
        public string PoliStart { get; set; }
        public Nullable<System.DateTime> PoliDate { get; set; }
        public string Sync { get; set; }
        public string Status { get; set; }
        public string Pocount { get; set; }
        public string userCode { get; set; }
        public Nullable<System.DateTime> CurrentDate { get; set; }
        public string UploadedSAP { get; set; }
    }
}
