//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMRthirty
    {
        public string cntrcode { get; set; }
        public string prd_year { get; set; }
        public string prd_season { get; set; }
        public string prd_code { get; set; }
        public string ppmsID { get; set; }
        public string PLDstatus { get; set; }
        public string grCode { get; set; }
        public string cmrtype { get; set; }
        public Nullable<double> existarea { get; set; }
        public Nullable<double> totFplant { get; set; }
        public Nullable<double> totMplant { get; set; }
        public Nullable<double> Pld_RejAce { get; set; }
        public string PldRejType { get; set; }
        public string Reason { get; set; }
        public string existBoll { get; set; }
        public Nullable<int> Exp_Boll { get; set; }
        public Nullable<double> Boll_wt { get; set; }
        public Nullable<double> Kaps_picked { get; set; }
        public string Roughcount { get; set; }
        public string Roughtype { get; set; }
        public Nullable<int> MRoughcount { get; set; }
        public string MRoughtype { get; set; }
        public Nullable<System.DateTime> crossDate { get; set; }
        public string CrossStatus { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> DateVisit { get; set; }
        public string obr_Recomd { get; set; }
        public string ExpYield { get; set; }
        public Nullable<System.DateTime> PoliCloseDt { get; set; }
        public string Fline { get; set; }
        public string Sync { get; set; }
        public string Shedder { get; set; }
        public Nullable<System.DateTime> GADt1 { get; set; }
        public Nullable<System.DateTime> GADt2 { get; set; }
        public Nullable<System.DateTime> GADt3 { get; set; }
        public string Fdos1 { get; set; }
        public string Fdos2 { get; set; }
        public string Fdos3 { get; set; }
        public string Mdos1 { get; set; }
        public string Mdos2 { get; set; }
        public string Mdos3 { get; set; }
        public string Othchemical { get; set; }
        public Nullable<System.DateTime> OthDt { get; set; }
        public string OthFdos { get; set; }
        public string OthMdos { get; set; }
        public string Status { get; set; }
        public string Pocount { get; set; }
        public string usercode { get; set; }
        public Nullable<System.DateTime> CurrentDate { get; set; }
        public string UploadedSAP { get; set; }
    }
}
