//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class common_My_Travle_Start
    {
        public long tr_id { get; set; }
        public string mdocode { get; set; }
        public string coordinate { get; set; }
        public string startaddress { get; set; }
        public string startdate { get; set; }
        public string imgname { get; set; }
        public string imgpath { get; set; }
        public string Status { get; set; }
        public string txtkm { get; set; }
        public string place { get; set; }
        public string purpose { get; set; }
        public string imgstatus { get; set; }
        public string vehicletype { get; set; }
        public Nullable<System.DateTime> tr_date { get; set; }
    }
}
