//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crop_Factor
    {
        public string Prd_year { get; set; }
        public string Prd_season { get; set; }
        public string Cntr_code { get; set; }
        public string Prd_code { get; set; }
        public string factor { get; set; }
    }
}
