//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distance_Master
    {
        public string Cntr_abbr { get; set; }
        public string cls_code { get; set; }
        public string vil_code { get; set; }
        public Nullable<float> dis_cls_cntr { get; set; }
        public Nullable<float> dis_vil_cls_hq { get; set; }
        public Nullable<float> dis_vil_cntr_hq { get; set; }
    }
}
