//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOP_Comp_Details
    {
        public string Reg_code { get; set; }
        public string Cntr_abbr { get; set; }
        public string Prd_Code { get; set; }
        public string DOP_Early { get; set; }
        public string DOP_Normal { get; set; }
        public string DOP_Late { get; set; }
        public string Comp_Crop_a { get; set; }
        public Nullable<float> Comp_Crop_a_price { get; set; }
        public string Comp_Crop_b { get; set; }
        public Nullable<float> Comp_Crop_b_price { get; set; }
        public string Comp_SdCrop { get; set; }
        public Nullable<float> Comp_SdCrop_price { get; set; }
        public Nullable<float> Cult_Cost { get; set; }
    }
}
