//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTL_ContractData
    {
        public int TrId { get; set; }
        public string GrowerName { get; set; }
        public string FatherName { get; set; }
        public string Village { get; set; }
        public string Taluka { get; set; }
        public string District { get; set; }
        public string CntrYear { get; set; }
        public string Crop { get; set; }
        public string Acre { get; set; }
        public string Place { get; set; }
        public string PlanAcre { get; set; }
        public string RsRate { get; set; }
        public string RsWords { get; set; }
        public string RegFees { get; set; }
        public string RegFeeWord { get; set; }
        public string Season { get; set; }
        public string GrowerSign { get; set; }
        public string ContDate { get; set; }
        public string SignPlace { get; set; }
        public string OrderNo { get; set; }
        public string Branch { get; set; }
        public string Dt { get; set; }
        public string CntrMonth { get; set; }
        public string DtYear { get; set; }
        public string Age { get; set; }
        public string FromDt { get; set; }
        public string Moisture { get; set; }
        public string Growing { get; set; }
        public string Clean { get; set; }
        public string MinDistance { get; set; }
        public string GrwrAddress { get; set; }
        public string Vit1Name { get; set; }
        public string Vit1Address { get; set; }
        public string Vit1Village { get; set; }
        public string Vit1Taluka { get; set; }
        public string Vit1District { get; set; }
        public string Vit2Name { get; set; }
        public string Vit2Address { get; set; }
        public string Vit2Village { get; set; }
        public string Vit2Taluka { get; set; }
        public string Vit2District { get; set; }
        public string MailId { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> TrDate { get; set; }
    }
}
