//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public int TrId { get; set; }
        public string EmpCode { get; set; }
        public string Module { get; set; }
        public string ActionPerformed { get; set; }
        public string ErrorOccured { get; set; }
        public Nullable<System.DateTime> TrDate { get; set; }
    }
}
