//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXT_Fruit_TblUserMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EXT_Fruit_TblUserMaster()
        {
            this.EXT_Fruit_TblTransctionMaster = new HashSet<EXT_Fruit_TblTransctionMaster>();
        }
    
        public long Id { get; set; }
        public string firstName { get; set; }
        public string middleName { get; set; }
        public string lastName { get; set; }
        public string email { get; set; }
        public string mobileNo { get; set; }
        public string password { get; set; }
        public string aadharNo { get; set; }
        public string occupation { get; set; }
        public string userImage { get; set; }
        public string address { get; set; }
        public string OTP { get; set; }
        public string IMEI { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> Flag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXT_Fruit_TblTransctionMaster> EXT_Fruit_TblTransctionMaster { get; set; }
    }
}
