//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXT_TblCropProductMaster
    {
        public long productID { get; set; }
        public string productName { get; set; }
        public Nullable<decimal> pricePerQty { get; set; }
        public string productImageName { get; set; }
        public Nullable<long> cropCategoryID { get; set; }
        public Nullable<long> createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<int> flag { get; set; }
        public string cropName { get; set; }
    
        public virtual EXT_TblCropCategoryMaster EXT_TblCropCategoryMaster { get; set; }
    }
}
