//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXT_TblQuestionMaster
    {
        public long questionID { get; set; }
        public Nullable<long> userID { get; set; }
        public string Question { get; set; }
        public string VideoName { get; set; }
        public string PhotoName { get; set; }
        public Nullable<System.DateTime> TrDate { get; set; }
        public byte[] Video { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<int> Flag { get; set; }
    }
}
