//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXT_TblPostMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EXT_TblPostMaster()
        {
            this.EXT_TblPostCommentMaster = new HashSet<EXT_TblPostCommentMaster>();
            this.EXT_TblPostLikeMaster = new HashSet<EXT_TblPostLikeMaster>();
        }
    
        public long postID { get; set; }
        public Nullable<long> userID { get; set; }
        public string Heading { get; set; }
        public string ContentStr { get; set; }
        public byte[] Video { get; set; }
        public string VideoName { get; set; }
        public byte[] Photo { get; set; }
        public string PhotoName { get; set; }
        public string TypeOfPost { get; set; }
        public Nullable<System.DateTime> TrDate { get; set; }
        public Nullable<int> Flag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXT_TblPostCommentMaster> EXT_TblPostCommentMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXT_TblPostLikeMaster> EXT_TblPostLikeMaster { get; set; }
    }
}
