//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXT_TblAnswerMaster
    {
        public long answerID { get; set; }
        public Nullable<long> userID { get; set; }
        public string answerContent { get; set; }
        public Nullable<System.DateTime> trDate { get; set; }
        public Nullable<int> Flag { get; set; }
        public Nullable<long> questionID { get; set; }
    }
}
