//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXT_TblFarmerMaster
    {
        public long TrId { get; set; }
        public string Name { get; set; }
        public string email { get; set; }
        public string mobileNo { get; set; }
        public string aadharNo { get; set; }
        public string occupation { get; set; }
        public string cropsCultivated { get; set; }
        public string landHoldingArea { get; set; }
        public string state { get; set; }
        public string district { get; set; }
        public string taluka { get; set; }
        public string village { get; set; }
        public string pinCode { get; set; }
        public string altitudeOfLand { get; set; }
        public string userImage { get; set; }
        public Nullable<System.DateTime> TrDate { get; set; }
        public Nullable<int> Flag { get; set; }
        public string password { get; set; }
        public string IMEI { get; set; }
        public string OTP { get; set; }
    }
}
