//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXT_TblSessionUserMaster
    {
        public long Id { get; set; }
        public Nullable<long> userID { get; set; }
        public Nullable<int> sessionTime { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> statusFlag { get; set; }
    }
}
