//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXT_TblFutureVideoMaster
    {
        public long vID { get; set; }
        public Nullable<long> userID { get; set; }
        public string videoTitle { get; set; }
        public string videoUrl { get; set; }
        public string videoDescription { get; set; }
        public byte[] video { get; set; }
        public string videoName { get; set; }
        public Nullable<System.DateTime> TrDate { get; set; }
        public Nullable<int> Flag { get; set; }
    }
}
