//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FarmerCommentDetail
    {
        public int RowId { get; set; }
        public Nullable<int> IssueId { get; set; }
        public string FarmerID { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string CommentsBy { get; set; }
    }
}
