//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farmer_SalesPlanMaster
    {
        public int TrId { get; set; }
        public string Crop { get; set; }
        public string Variety { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public int Week { get; set; }
        public Nullable<double> SalesPlan { get; set; }
        public string PlannedBy { get; set; }
        public string PlannedById { get; set; }
        public string Status { get; set; }
        public int Flag { get; set; }
        public System.DateTime TrDate { get; set; }
    }
}
