//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farmer_Retailer
    {
        public short Rid { get; set; }
        public string RitID { get; set; }
        public string RetName { get; set; }
        public string RetLocan { get; set; }
        public string RetPassword { get; set; }
        public Nullable<short> Flag { get; set; }
    }
}
