//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farmer_OrderSeedsmaster
    {
        public int id { get; set; }
        public string Crop { get; set; }
        public string OrderType { get; set; }
        public string Variety { get; set; }
        public Nullable<int> advanceplantcount { get; set; }
        public Nullable<int> balancePlantCost { get; set; }
        public Nullable<int> perplantcost { get; set; }
        public string month { get; set; }
        public string week { get; set; }
        public Nullable<int> plantstock { get; set; }
        public string year { get; set; }
        public Nullable<int> status { get; set; }
        public System.DateTime TrDate { get; set; }
    }
}
