//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farmer_SeedDispatchDetail
    {
        public int TrId { get; set; }
        public int OrderNo { get; set; }
        public Nullable<int> BalanceQty { get; set; }
        public Nullable<int> DispatchQty { get; set; }
        public Nullable<System.DateTime> DispatchDate { get; set; }
        public string DispatchById { get; set; }
        public string DispatchBy { get; set; }
        public string DispatchedTo { get; set; }
        public string Remark { get; set; }
        public int Flag { get; set; }
        public System.DateTime TrDate { get; set; }
    }
}
