//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farmer_addressDetail
    {
        public string mobileno { get; set; }
        public string state { get; set; }
        public string dist { get; set; }
        public string taluka { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string farmername { get; set; }
        public string pincode { get; set; }
        public string aadharno { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.DateTime> updatedate { get; set; }
    }
}
