//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farmer_Regionwise_PlantCost
    {
        public int TrId { get; set; }
        public string Region { get; set; }
        public double PerPlantCost { get; set; }
        public int Flag { get; set; }
        public System.DateTime TrDate { get; set; }
    }
}
