//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farmer_ProductMaster
    {
        public string cropname { get; set; }
        public string productname { get; set; }
        public string productcode { get; set; }
        public Nullable<double> productprice { get; set; }
    }
}
