//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farmer_couponActivation
    {
        public int id { get; set; }
        public string mdocode { get; set; }
        public string couponcode { get; set; }
        public string far_mobileno { get; set; }
        public string year { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> entrydate { get; set; }
    }
}
