//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farmer_Sow_Harvest_date
    {
        public int id { get; set; }
        public Nullable<int> farmerId { get; set; }
        public string prd_code { get; set; }
        public string prd_year { get; set; }
        public Nullable<System.DateTime> showingDate { get; set; }
        public Nullable<System.DateTime> harvestingDate { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> modifyDate { get; set; }
        public string type { get; set; }
        public string mobileno { get; set; }
        public string irrigation { get; set; }
        public string crop { get; set; }
    }
}
