//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FarmerIssueDetail
    {
        public int ID { get; set; }
        public string FarmerID { get; set; }
        public string CropType { get; set; }
        public string ImgIssue { get; set; }
        public string IssueDesc { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
