//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farmer_SeedlingMaster
    {
        public int Rid { get; set; }
        public string FarmerID { get; set; }
        public string FarmerName { get; set; }
        public string MobileNo { get; set; }
        public string Address1 { get; set; }
        public string Landmark { get; set; }
        public string Place { get; set; }
        public string VillageName { get; set; }
        public string TalukaName { get; set; }
        public string DisctrictName { get; set; }
        public string StateName { get; set; }
        public Nullable<int> Pincode { get; set; }
        public string AdharNo { get; set; }
        public string Remarks { get; set; }
        public string UserType { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<byte> Flag { get; set; }
    }
}
