//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farmer_CropMaster
    {
        public byte Rid { get; set; }
        public string CropName { get; set; }
        public string Variety { get; set; }
        public Nullable<decimal> PlantCost { get; set; }
        public Nullable<decimal> AdvanceAmt { get; set; }
        public Nullable<byte> Flag { get; set; }
    }
}
