//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farmer_PaymentHistorylog
    {
        public long id { get; set; }
        public string mihpayid { get; set; }
        public string mode { get; set; }
        public string status { get; set; }
        public string unmappedstatus { get; set; }
        public string txnid { get; set; }
        public string amount { get; set; }
        public string cardCategory { get; set; }
        public string discount { get; set; }
        public string net_amount_debit { get; set; }
        public string addedon { get; set; }
        public string productinfo { get; set; }
        public string firstname { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string udf1 { get; set; }
        public string udf2 { get; set; }
        public string udf3 { get; set; }
        public string udf4 { get; set; }
        public string udf5 { get; set; }
        public string hash { get; set; }
        public string payment_source { get; set; }
        public string PG_TYPE { get; set; }
        public string ibibo_code { get; set; }
        public string error_code { get; set; }
        public string Error_Message { get; set; }
        public string card_no { get; set; }
        public Nullable<System.DateTime> entrydate { get; set; }
    }
}
