//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farmer_seedbookDetail
    {
        public int OrderNo { get; set; }
        public string FarmerId { get; set; }
        public string PayMode { get; set; }
        public string PaymentDet { get; set; }
        public string BookById { get; set; }
        public string BookedBy { get; set; }
        public string BookingDate { get; set; }
        public string Crop { get; set; }
        public string Variety { get; set; }
        public string Year { get; set; }
        public string Month { get; set; }
        public string Week { get; set; }
        public string QTY { get; set; }
        public string Remark { get; set; }
        public string ordertype { get; set; }
        public string userid { get; set; }
        public string address { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> entrydate { get; set; }
        public Nullable<byte> Flag { get; set; }
        public Nullable<decimal> AdvAmtReceived { get; set; }
        public Nullable<decimal> BalanceAmt { get; set; }
        public Nullable<System.DateTime> AdvRecDate { get; set; }
        public Nullable<System.DateTime> BalanceDate { get; set; }
    }
}
