//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farmer_Coupon
    {
        public int Rid { get; set; }
        public short ProdYear { get; set; }
        public string cropType { get; set; }
        public string ProductName { get; set; }
        public string Discount { get; set; }
        public string PicName { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
