//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farmer_TransactionIdMaster
    {
        public long id { get; set; }
        public string mobileno { get; set; }
        public string transactionId { get; set; }
        public string payment_status { get; set; }
        public string paymentid { get; set; }
        public string mode { get; set; }
        public string Error_Message { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string order_status { get; set; }
    }
}
