//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FM_BreakDownDetail
    {
        public int id { get; set; }
        public string machineno { get; set; }
        public string type { get; set; }
        public string issue { get; set; }
        public string issuereply { get; set; }
        public string createyby { get; set; }
        public Nullable<System.DateTime> issuedate { get; set; }
        public Nullable<System.DateTime> entrydate { get; set; }
        public string asignto { get; set; }
        public string replyby { get; set; }
        public Nullable<System.DateTime> replaydate { get; set; }
        public string actiontype { get; set; }
    }
}
