//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FM_CardFeedbackdetail
    {
        public int id { get; set; }
        public string CardNo { get; set; }
        public string satisfiedstatus { get; set; }
        public string recommendstatus { get; set; }
        public string servicefuturestatus { get; set; }
        public string suggestion { get; set; }
        public Nullable<System.DateTime> entrydate { get; set; }
        public string entryby { get; set; }
    }
}
