//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FM_Farmer_Master
    {
        public int tr_id { get; set; }
        public string name { get; set; }
        public string mobile { get; set; }
        public string aadhar { get; set; }
        public string state { get; set; }
        public string district { get; set; }
        public string taluka { get; set; }
        public string village { get; set; }
        public string pincode { get; set; }
        public string adviser_name { get; set; }
        public string user_code { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string crop { get; set; }
        public string sowingDate { get; set; }
        public string harvestingDate { get; set; }
        public string remark { get; set; }
        public string SAP_CUST_NO { get; set; }
        public string SAP_msg { get; set; }
        public string SAP_Tran_Type { get; set; }
        public string SAP_Mesg_Type { get; set; }
        public string SAP_Mesg_id { get; set; }
        public string SAP_Mesg_no { get; set; }
        public Nullable<int> SAP_ID_Create { get; set; }
    }
}
