//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FM_Farmer_Details
    {
        public int tr_id { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string mobile { get; set; }
        public string aadhar { get; set; }
        public string state { get; set; }
        public string district { get; set; }
        public string taluka { get; set; }
        public string village { get; set; }
        public string pincode { get; set; }
        public string crop { get; set; }
        public string operation { get; set; }
        public string area { get; set; }
        public string charges { get; set; }
        public string totalcharges { get; set; }
        public string opstarttime { get; set; }
        public string opendtime { get; set; }
        public string coordinate { get; set; }
        public string activitydate { get; set; }
        public string adviser_name { get; set; }
        public string user_code { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.DateTime> uploadDate { get; set; }
    }
}
