//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FM_JobCardDetail
    {
        public int CardID { get; set; }
        public string farmerid { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MobileNo { get; set; }
        public string state { get; set; }
        public string dist { get; set; }
        public string taluka { get; set; }
        public string village { get; set; }
        public string FarmName { get; set; }
        public string FarmLocation { get; set; }
        public string FarmArea { get; set; }
        public string Crop { get; set; }
        public string Operation { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> servicedate { get; set; }
        public string flexibilityNo { get; set; }
        public Nullable<System.DateTime> entrydate { get; set; }
        public string entryby { get; set; }
        public string Coordinate { get; set; }
        public string tagstatus { get; set; }
        public Nullable<System.DateTime> tagdate { get; set; }
        public string tagarea { get; set; }
        public string payment { get; set; }
        public string chargesperguntha { get; set; }
        public Nullable<System.DateTime> paymentdate { get; set; }
        public string payamount { get; set; }
        public string paymentdetail { get; set; }
        public string areaType { get; set; }
        public string paymentFlag { get; set; }
    }
}
