//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FM_SA_Details
    {
        public int tr_id { get; set; }
        public string sa_name { get; set; }
        public string sa_lastName { get; set; }
        public string Mobile_no { get; set; }
        public string Aadhar_no { get; set; }
        public string bank { get; set; }
        public string b_name { get; set; }
        public string account_no { get; set; }
        public string ifsc_code { get; set; }
        public string active { get; set; }
        public string type { get; set; }
        public string otp { get; set; }
        public Nullable<System.DateTime> r_date { get; set; }
        public string state { get; set; }
        public string district { get; set; }
        public string taluka { get; set; }
        public string village { get; set; }
        public string pincode { get; set; }
    }
}
