//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FM_ServiceOperatorJobList
    {
        public int rowid { get; set; }
        public int CardID { get; set; }
        public string OperatorID { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> jobentrydate { get; set; }
        public Nullable<System.DateTime> jobcompletedate { get; set; }
        public string machineno { get; set; }
        public string starttime { get; set; }
        public string endtime { get; set; }
        public Nullable<decimal> amountpaid { get; set; }
        public string repaireandmaintance { get; set; }
        public Nullable<System.DateTime> updatedt { get; set; }
        public string promotorId { get; set; }
    }
}
