//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Former_ProductDescription
    {
        public int ÌD { get; set; }
        public string CropType { get; set; }
        public string CropName { get; set; }
        public string Lang { get; set; }
        public string ProductName { get; set; }
        public string ProductDesc { get; set; }
        public string PicName { get; set; }
        public string Code { get; set; }
        public string Costperacre { get; set; }
        public string SeedRate { get; set; }
        public string Sowing_Season { get; set; }
    }
}
