//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Former_PageTextDetail
    {
        public int ID { get; set; }
        public string Pagename { get; set; }
        public string PageID { get; set; }
        public Nullable<int> LangID { get; set; }
        public string Langname { get; set; }
        public string LabelName { get; set; }
        public string LabelText { get; set; }
    }
}
