//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class fsdist_vgrowerbatchupdateDelete
    {
        public decimal gr_id { get; set; }
        public string batch_no { get; set; }
        public string bprd_catg { get; set; }
        public string bprd_code { get; set; }
        public Nullable<double> bprd_acre { get; set; }
        public Nullable<System.DateTime> action_date { get; set; }
        public string action { get; set; }
    }
}
