//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class fsdist_usermaster
    {
        public decimal User_id { get; set; }
        public string user_code { get; set; }
        public string user_name { get; set; }
        public string user_pwd { get; set; }
        public string user_role { get; set; }
        public string user_desg { get; set; }
        public string user_email { get; set; }
        public string user_status { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string createby { get; set; }
        public string modifyby { get; set; }
        public Nullable<byte> IsLogedIn { get; set; }
        public Nullable<byte> LoginCount { get; set; }
        public Nullable<byte> AccountLocked { get; set; }
        public string UserToken { get; set; }
        public string LoginBy { get; set; }
    }
}
