//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class fsdist_staffdetail
    {
        public decimal id { get; set; }
        public string cntr_code { get; set; }
        public string prd_year { get; set; }
        public string prd_season { get; set; }
        public string mattype { get; set; }
        public string vil_code { get; set; }
        public string staff_code { get; set; }
        public string TFA_code { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
