//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FSStatusLog
    {
        public long rowID { get; set; }
        public string ppmsID { get; set; }
        public string pono { get; set; }
        public string SAPstatus { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
    }
}
