//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GrowOnlineDevEntities : DbContext
    {
        public GrowOnlineDevEntities()
            : base("name=GrowOnlineDevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<District_Master> District_Master { get; set; }
        public virtual DbSet<Shop_CartInfo> Shop_CartInfo { get; set; }
        public virtual DbSet<shop_ContactUs> shop_ContactUs { get; set; }
        public virtual DbSet<Shop_Order_Details> Shop_Order_Details { get; set; }
        public virtual DbSet<Shop_OrderProductDetails> Shop_OrderProductDetails { get; set; }
        public virtual DbSet<Shop_Product_Master> Shop_Product_Master { get; set; }
        public virtual DbSet<Shop_Retailer_UserMaster> Shop_Retailer_UserMaster { get; set; }
        public virtual DbSet<Shop_Shipping_address> Shop_Shipping_address { get; set; }
        public virtual DbSet<Shop_State_Master> Shop_State_Master { get; set; }
        public virtual DbSet<State_Master> State_Master { get; set; }
        public virtual DbSet<User_Wallet> User_Wallet { get; set; }
        public virtual DbSet<User_Wallet_LogInfo> User_Wallet_LogInfo { get; set; }
        public virtual DbSet<UserWallet> UserWallet { get; set; }
        public virtual DbSet<Village_Master> Village_Master { get; set; }
        public virtual DbSet<shop_catagory> shop_catagory { get; set; }
        public virtual DbSet<shop_cmp_image> shop_cmp_image { get; set; }
        public virtual DbSet<shop_crop_rank> shop_crop_rank { get; set; }
        public virtual DbSet<shop_crops> shop_crops { get; set; }
        public virtual DbSet<Shop_District_Master> Shop_District_Master { get; set; }
        public virtual DbSet<Shop_Feedback> Shop_Feedback { get; set; }
        public virtual DbSet<shop_manufacture_master> shop_manufacture_master { get; set; }
        public virtual DbSet<Shop_New_District_Master> Shop_New_District_Master { get; set; }
        public virtual DbSet<Shop_New_State_Master> Shop_New_State_Master { get; set; }
        public virtual DbSet<Shop_New_Taluka_Master> Shop_New_Taluka_Master { get; set; }
        public virtual DbSet<Shop_New_Village_Master> Shop_New_Village_Master { get; set; }
        public virtual DbSet<shop_order_dispatch> shop_order_dispatch { get; set; }
        public virtual DbSet<Shop_Order_ErrorLogDetails> Shop_Order_ErrorLogDetails { get; set; }
        public virtual DbSet<Shop_OrderLogDetails> Shop_OrderLogDetails { get; set; }
    }
}
