//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grower_Master
    {
        public string gr_code { get; set; }
        public string gr_name { get; set; }
        public string hof_code { get; set; }
        public string vil_code { get; set; }
        public string cls_code { get; set; }
        public string talq_code { get; set; }
        public string Dist_code { get; set; }
        public string Stat_code { get; set; }
        public string cntr_abbr { get; set; }
    }
}
