//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GrowOnlineDevEntities : DbContext
    {
        public GrowOnlineDevEntities()
            : base("name=GrowOnlineDevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area_loss> Area_loss { get; set; }
        public virtual DbSet<Center_target> Center_target { get; set; }
        public virtual DbSet<Center_target2> Center_target2 { get; set; }
        public virtual DbSet<Centre_Master> Centre_Master { get; set; }
        public virtual DbSet<Centre_Prodty> Centre_Prodty { get; set; }
        public virtual DbSet<Centre_Range> Centre_Range { get; set; }
        public virtual DbSet<Cluster_Master> Cluster_Master { get; set; }
        public virtual DbSet<Cluster_master_log> Cluster_master_log { get; set; }
        public virtual DbSet<Cluster_Prodty> Cluster_Prodty { get; set; }
        public virtual DbSet<Cluster_target> Cluster_target { get; set; }
        public virtual DbSet<Cntr_Abbr_Master> Cntr_Abbr_Master { get; set; }
        public virtual DbSet<Component_Master> Component_Master { get; set; }
        public virtual DbSet<CostCenterMaster> CostCenterMaster { get; set; }
        public virtual DbSet<Crop_Master> Crop_Master { get; set; }
        public virtual DbSet<Distance_Master> Distance_Master { get; set; }
        public virtual DbSet<District_Master> District_Master { get; set; }
        public virtual DbSet<DOP_Comp_Details> DOP_Comp_Details { get; set; }
        public virtual DbSet<dtproperties> dtproperties { get; set; }
        public virtual DbSet<EXT_Fruit_TblFruitMaster> EXT_Fruit_TblFruitMaster { get; set; }
        public virtual DbSet<EXT_Fruit_TblTransctionMaster> EXT_Fruit_TblTransctionMaster { get; set; }
        public virtual DbSet<EXT_Fruit_TblUserMaster> EXT_Fruit_TblUserMaster { get; set; }
        public virtual DbSet<EXT_TblAnswerCommentMaster> EXT_TblAnswerCommentMaster { get; set; }
        public virtual DbSet<EXT_TblAnswerMaster> EXT_TblAnswerMaster { get; set; }
        public virtual DbSet<EXT_TblCropCategoryMaster> EXT_TblCropCategoryMaster { get; set; }
        public virtual DbSet<EXT_TblCropMaster> EXT_TblCropMaster { get; set; }
        public virtual DbSet<EXT_TblCropProductMaster> EXT_TblCropProductMaster { get; set; }
        public virtual DbSet<EXT_TblEventPlanningMaster> EXT_TblEventPlanningMaster { get; set; }
        public virtual DbSet<EXT_TblFarmerMaster> EXT_TblFarmerMaster { get; set; }
        public virtual DbSet<EXT_TblFutureVideoMaster> EXT_TblFutureVideoMaster { get; set; }
        public virtual DbSet<EXT_TblPostCommentMaster> EXT_TblPostCommentMaster { get; set; }
        public virtual DbSet<EXT_TblPostLikeMaster> EXT_TblPostLikeMaster { get; set; }
        public virtual DbSet<EXT_TblPostMaster> EXT_TblPostMaster { get; set; }
        public virtual DbSet<EXT_TblProductCropMaster> EXT_TblProductCropMaster { get; set; }
        public virtual DbSet<EXT_TblProductTransactionMaster> EXT_TblProductTransactionMaster { get; set; }
        public virtual DbSet<EXT_TblQuestionMaster> EXT_TblQuestionMaster { get; set; }
        public virtual DbSet<EXT_TblSessionUserMaster> EXT_TblSessionUserMaster { get; set; }
        public virtual DbSet<EXT_TblTransactionStatusMaster> EXT_TblTransactionStatusMaster { get; set; }
        public virtual DbSet<EXT_TblUserMaster> EXT_TblUserMaster { get; set; }
        public virtual DbSet<Farmer_addressDetail> Farmer_addressDetail { get; set; }
        public virtual DbSet<Farmer_couponActivation> Farmer_couponActivation { get; set; }
        public virtual DbSet<Farmer_Details> Farmer_Details { get; set; }
        public virtual DbSet<Farmer_ProductMaster> Farmer_ProductMaster { get; set; }
        public virtual DbSet<Farmer_Retailer> Farmer_Retailer { get; set; }
        public virtual DbSet<Farmer_SeedlingMaster> Farmer_SeedlingMaster { get; set; }
        public virtual DbSet<Farmer_TransactionIdMaster> Farmer_TransactionIdMaster { get; set; }
        public virtual DbSet<Farmer_VisitReq> Farmer_VisitReq { get; set; }
        public virtual DbSet<FM_Farmer_Master> FM_Farmer_Master { get; set; }
        public virtual DbSet<FM_ServiceOperatorJobList> FM_ServiceOperatorJobList { get; set; }
        public virtual DbSet<FM_User_Details> FM_User_Details { get; set; }
        public virtual DbSet<FMS_TransactionIdMaster> FMS_TransactionIdMaster { get; set; }
        public virtual DbSet<FSStatusLog> FSStatusLog { get; set; }
        public virtual DbSet<Grower_blacklist> Grower_blacklist { get; set; }
        public virtual DbSet<Grower_Master> Grower_Master { get; set; }
        public virtual DbSet<Hof_Centre_Range> Hof_Centre_Range { get; set; }
        public virtual DbSet<hof_overall_score> hof_overall_score { get; set; }
        public virtual DbSet<Hof_Score> Hof_Score { get; set; }
        public virtual DbSet<Hof_target> Hof_target { get; set; }
        public virtual DbSet<Login_Tbl> Login_Tbl { get; set; }
        public virtual DbSet<MO_Coupan> MO_Coupan { get; set; }
        public virtual DbSet<MO_POGSAP> MO_POGSAP { get; set; }
        public virtual DbSet<National_target> National_target { get; set; }
        public virtual DbSet<NewDistrict_Master> NewDistrict_Master { get; set; }
        public virtual DbSet<NewVendorCreation> NewVendorCreation { get; set; }
        public virtual DbSet<NTaluka_Master> NTaluka_Master { get; set; }
        public virtual DbSet<OldSystemPOCreate> OldSystemPOCreate { get; set; }
        public virtual DbSet<Parcel_Master> Parcel_Master { get; set; }
        public virtual DbSet<POCreateDetail> POCreateDetail { get; set; }
        public virtual DbSet<POStatusLog> POStatusLog { get; set; }
        public virtual DbSet<Processing_Loss> Processing_Loss { get; set; }
        public virtual DbSet<Processing_loss_cot> Processing_loss_cot { get; set; }
        public virtual DbSet<Procurement_Price> Procurement_Price { get; set; }
        public virtual DbSet<Region_Master> Region_Master { get; set; }
        public virtual DbSet<Region_Prodty> Region_Prodty { get; set; }
        public virtual DbSet<Region_target> Region_target { get; set; }
        public virtual DbSet<RegionDetails> RegionDetails { get; set; }
        public virtual DbSet<Resource_Master> Resource_Master { get; set; }
        public virtual DbSet<Retailer_TBMDist> Retailer_TBMDist { get; set; }
        public virtual DbSet<sap_cluster_master> sap_cluster_master { get; set; }
        public virtual DbSet<sapcmr_data> sapcmr_data { get; set; }
        public virtual DbSet<Saprfc_log> Saprfc_log { get; set; }
        public virtual DbSet<Score_Data> Score_Data { get; set; }
        public virtual DbSet<Shop_CartInfo> Shop_CartInfo { get; set; }
        public virtual DbSet<shop_ContactUs> shop_ContactUs { get; set; }
        public virtual DbSet<Shop_Order_Details> Shop_Order_Details { get; set; }
        public virtual DbSet<Shop_OrderProductDetails> Shop_OrderProductDetails { get; set; }
        public virtual DbSet<Shop_Product_Master> Shop_Product_Master { get; set; }
        public virtual DbSet<Shop_Retailer_UserMaster> Shop_Retailer_UserMaster { get; set; }
        public virtual DbSet<shop_retailer_usermaster_passive_users_tmp> shop_retailer_usermaster_passive_users_tmp { get; set; }
        public virtual DbSet<Shop_Shipping_address> Shop_Shipping_address { get; set; }
        public virtual DbSet<Shop_State_Master> Shop_State_Master { get; set; }
        public virtual DbSet<State_Master> State_Master { get; set; }
        public virtual DbSet<Taluka_Master> Taluka_Master { get; set; }
        public virtual DbSet<Temp_Farmer_Details> Temp_Farmer_Details { get; set; }
        public virtual DbSet<temp_hofmaster> temp_hofmaster { get; set; }
        public virtual DbSet<temp_parcelmaster> temp_parcelmaster { get; set; }
        public virtual DbSet<Test_Rejection> Test_Rejection { get; set; }
        public virtual DbSet<Unit_Master> Unit_Master { get; set; }
        public virtual DbSet<upload_Growerblacklist> upload_Growerblacklist { get; set; }
        public virtual DbSet<User_authorization> User_authorization { get; set; }
        public virtual DbSet<User_Master> User_Master { get; set; }
        public virtual DbSet<User_Tran_Auth> User_Tran_Auth { get; set; }
        public virtual DbSet<user_transaction> user_transaction { get; set; }
        public virtual DbSet<User_Wallet> User_Wallet { get; set; }
        public virtual DbSet<User_Wallet_LogInfo> User_Wallet_LogInfo { get; set; }
        public virtual DbSet<UserWallet> UserWallet { get; set; }
        public virtual DbSet<Village_Master> Village_Master { get; set; }
        public virtual DbSet<Village_Masterold> Village_Masterold { get; set; }
        public virtual DbSet<village_prodty> village_prodty { get; set; }
        public virtual DbSet<Year_Season_Master> Year_Season_Master { get; set; }
        public virtual DbSet<AuditLog> AuditLog { get; set; }
        public virtual DbSet<CMRforty> CMRforty { get; set; }
        public virtual DbSet<CMRten> CMRten { get; set; }
        public virtual DbSet<CMRthirty> CMRthirty { get; set; }
        public virtual DbSet<CMRtwently> CMRtwently { get; set; }
        public virtual DbSet<Common_My_travle_AddPlace> Common_My_travle_AddPlace { get; set; }
        public virtual DbSet<Common_My_Travle_End> Common_My_Travle_End { get; set; }
        public virtual DbSet<common_My_Travle_Start> common_My_Travle_Start { get; set; }
        public virtual DbSet<Crop_Factor> Crop_Factor { get; set; }
        public virtual DbSet<DirectCMRforty> DirectCMRforty { get; set; }
        public virtual DbSet<DirectCMRten> DirectCMRten { get; set; }
        public virtual DbSet<DirectCMRthirty> DirectCMRthirty { get; set; }
        public virtual DbSet<DirectCMRtwently> DirectCMRtwently { get; set; }
        public virtual DbSet<DTL_ContractData> DTL_ContractData { get; set; }
        public virtual DbSet<ErrorLog> ErrorLog { get; set; }
        public virtual DbSet<Farmer_Coupon> Farmer_Coupon { get; set; }
        public virtual DbSet<Farmer_CropMaster> Farmer_CropMaster { get; set; }
        public virtual DbSet<Farmer_OrderPaymentDetails> Farmer_OrderPaymentDetails { get; set; }
        public virtual DbSet<Farmer_OrderSeedsmaster> Farmer_OrderSeedsmaster { get; set; }
        public virtual DbSet<Farmer_PaymentHistorylog> Farmer_PaymentHistorylog { get; set; }
        public virtual DbSet<Farmer_Regionwise_PlantCost> Farmer_Regionwise_PlantCost { get; set; }
        public virtual DbSet<Farmer_SalesPlanMaster> Farmer_SalesPlanMaster { get; set; }
        public virtual DbSet<Farmer_seedbookDetail> Farmer_seedbookDetail { get; set; }
        public virtual DbSet<Farmer_SeedDispatchDetail> Farmer_SeedDispatchDetail { get; set; }
        public virtual DbSet<Farmer_Sow_Harvest_date> Farmer_Sow_Harvest_date { get; set; }
        public virtual DbSet<Farmer_TransactionIddetail> Farmer_TransactionIddetail { get; set; }
        public virtual DbSet<FarmerCommentDetail> FarmerCommentDetail { get; set; }
        public virtual DbSet<FarmerIssueDetail> FarmerIssueDetail { get; set; }
        public virtual DbSet<FM_BreakDownDetail> FM_BreakDownDetail { get; set; }
        public virtual DbSet<FM_CardFeedbackdetail> FM_CardFeedbackdetail { get; set; }
        public virtual DbSet<FM_DailyRoutineDetail> FM_DailyRoutineDetail { get; set; }
        public virtual DbSet<FM_Farmer_Details> FM_Farmer_Details { get; set; }
        public virtual DbSet<FM_JobCardDetail> FM_JobCardDetail { get; set; }
        public virtual DbSet<FM_MachineDetails> FM_MachineDetails { get; set; }
        public virtual DbSet<FM_SA_Details> FM_SA_Details { get; set; }
        public virtual DbSet<FM_UserMaster_Web> FM_UserMaster_Web { get; set; }
        public virtual DbSet<FMS_PaymentHistorylog> FMS_PaymentHistorylog { get; set; }
        public virtual DbSet<FMS_TransactionIddetail> FMS_TransactionIddetail { get; set; }
        public virtual DbSet<Former_PageTextDetail> Former_PageTextDetail { get; set; }
        public virtual DbSet<Former_ProductDescription> Former_ProductDescription { get; set; }
        public virtual DbSet<fsbatch_stock> fsbatch_stock { get; set; }
        public virtual DbSet<fsdist_batch> fsdist_batch { get; set; }
        public virtual DbSet<fsdist_cropauthorization> fsdist_cropauthorization { get; set; }
        public virtual DbSet<fsdist_data> fsdist_data { get; set; }
        public virtual DbSet<fsdist_groweracre> fsdist_groweracre { get; set; }
        public virtual DbSet<fsdist_groweracreupdateDelete> fsdist_groweracreupdateDelete { get; set; }
        public virtual DbSet<fsdist_POHistory> fsdist_POHistory { get; set; }
        public virtual DbSet<fsdist_staffdetail> fsdist_staffdetail { get; set; }
        public virtual DbSet<fsdist_subbatch> fsdist_subbatch { get; set; }
        public virtual DbSet<fsdist_suborgbatch> fsdist_suborgbatch { get; set; }
        public virtual DbSet<fsdist_suborgdata> fsdist_suborgdata { get; set; }
        public virtual DbSet<fsdist_usermaster> fsdist_usermaster { get; set; }
        public virtual DbSet<fsdist_VGrowerbatch> fsdist_VGrowerbatch { get; set; }
        public virtual DbSet<fsdist_vgrowerbatchupdateDelete> fsdist_vgrowerbatchupdateDelete { get; set; }
        public virtual DbSet<fsdist_villageacre> fsdist_villageacre { get; set; }
        public virtual DbSet<kuber_eligiblegrowerLists> kuber_eligiblegrowerLists { get; set; }
        public virtual DbSet<MDO_PaymentTransactionIddetail> MDO_PaymentTransactionIddetail { get; set; }
        public virtual DbSet<Mo_coupan1> Mo_coupan1 { get; set; }
        public virtual DbSet<MO_CoupanOLD> MO_CoupanOLD { get; set; }
        public virtual DbSet<Mo_POG> Mo_POG { get; set; }
        public virtual DbSet<MyTravel_AddPlace> MyTravel_AddPlace { get; set; }
        public virtual DbSet<MyTravel_End> MyTravel_End { get; set; }
        public virtual DbSet<MyTravel_Start> MyTravel_Start { get; set; }
        public virtual DbSet<Newcluster_Master> Newcluster_Master { get; set; }
        public virtual DbSet<NewDistinct_Master> NewDistinct_Master { get; set; }
        public virtual DbSet<NewGrower_Master> NewGrower_Master { get; set; }
        public virtual DbSet<Neworganizer_Master> Neworganizer_Master { get; set; }
        public virtual DbSet<Newsuborganizer_Master> Newsuborganizer_Master { get; set; }
        public virtual DbSet<Newtaluka_Master> Newtaluka_Master { get; set; }
        public virtual DbSet<NewVillage_Master> NewVillage_Master { get; set; }
        public virtual DbSet<oranizer_master1> oranizer_master1 { get; set; }
        public virtual DbSet<Phy_TagArea> Phy_TagArea { get; set; }
        public virtual DbSet<Phy_TagArea1> Phy_TagArea1 { get; set; }
        public virtual DbSet<PPMS_MenuPermission> PPMS_MenuPermission { get; set; }
        public virtual DbSet<Product_Master> Product_Master { get; set; }
        public virtual DbSet<ProgressEntry_CI> ProgressEntry_CI { get; set; }
        public virtual DbSet<ProgressEntry_RM> ProgressEntry_RM { get; set; }
        public virtual DbSet<ProgressEntry_ZM> ProgressEntry_ZM { get; set; }
        public virtual DbSet<ProgressEntryMaster> ProgressEntryMaster { get; set; }
        public virtual DbSet<RegisteredDevice> RegisteredDevice { get; set; }
        public virtual DbSet<Retailer_TBM> Retailer_TBM { get; set; }
        public virtual DbSet<SAPRegion_Master> SAPRegion_Master { get; set; }
        public virtual DbSet<shop_catagory> shop_catagory { get; set; }
        public virtual DbSet<shop_cmp_image> shop_cmp_image { get; set; }
        public virtual DbSet<shop_Courier_Details> shop_Courier_Details { get; set; }
        public virtual DbSet<shop_couriour_invoice> shop_couriour_invoice { get; set; }
        public virtual DbSet<shop_crops> shop_crops { get; set; }
        public virtual DbSet<Shop_Depo_Email> Shop_Depo_Email { get; set; }
        public virtual DbSet<shop_discountDetails> shop_discountDetails { get; set; }
        public virtual DbSet<Shop_District_Master> Shop_District_Master { get; set; }
        public virtual DbSet<Shop_Feedback> Shop_Feedback { get; set; }
        public virtual DbSet<shop_manufacture_master> shop_manufacture_master { get; set; }
        public virtual DbSet<Shop_New_District_Master> Shop_New_District_Master { get; set; }
        public virtual DbSet<Shop_New_State_Master> Shop_New_State_Master { get; set; }
        public virtual DbSet<Shop_New_Taluka_Master> Shop_New_Taluka_Master { get; set; }
        public virtual DbSet<Shop_New_Village_Master> Shop_New_Village_Master { get; set; }
        public virtual DbSet<shop_order_dispatch> shop_order_dispatch { get; set; }
        public virtual DbSet<Shop_Order_ErrorLogDetails> Shop_Order_ErrorLogDetails { get; set; }
        public virtual DbSet<Shop_OrderLogDetails> Shop_OrderLogDetails { get; set; }
        public virtual DbSet<shop_referalOrder> shop_referalOrder { get; set; }
        public virtual DbSet<shop_referalSave> shop_referalSave { get; set; }
        public virtual DbSet<shop_revalidation_details> shop_revalidation_details { get; set; }
        public virtual DbSet<shop_revalidation_order> shop_revalidation_order { get; set; }
        public virtual DbSet<shop_seedling_request> shop_seedling_request { get; set; }
        public virtual DbSet<shop_usermaster> shop_usermaster { get; set; }
        public virtual DbSet<Target_History> Target_History { get; set; }
        public virtual DbSet<tempData> tempData { get; set; }
        public virtual DbSet<upload_sapcmrdata> upload_sapcmrdata { get; set; }
        public virtual DbSet<user_log> user_log { get; set; }
        public virtual DbSet<village_esti_entry> village_esti_entry { get; set; }
        public virtual DbSet<Web_Mandi_usermaster> Web_Mandi_usermaster { get; set; }
    }
}
