//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grower_blacklist
    {
        public string gr_code { get; set; }
        public string ebeln { get; set; }
        public string ebelp { get; set; }
        public string cntr_code { get; set; }
        public string prd_year { get; set; }
        public string prd_season { get; set; }
        public string prd_code { get; set; }
        public string charg { get; set; }
        public byte parcel_Code { get; set; }
        public float exist_area { get; set; }
        public double unp_qty { get; set; }
        public float ger_per { get; set; }
        public float got_per { get; set; }
        public string Field1 { get; set; }
        public string Field2 { get; set; }
    }
}
