//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hof_Score
    {
        public string Cntr_code { get; set; }
        public string prd_year { get; set; }
        public string Prd_season { get; set; }
        public string prd_code { get; set; }
        public string hof_code { get; set; }
        public byte Parcel_Code { get; set; }
        public Nullable<float> issue_area { get; set; }
        public Nullable<double> unp_qty { get; set; }
        public Nullable<float> Prd_vity { get; set; }
        public Nullable<float> hof_score1 { get; set; }
        public string hof_cnt_Catg { get; set; }
        public string Cls_code { get; set; }
    }
}
