//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hof_overall_score
    {
        public string hof_code { get; set; }
        public string Prd_year { get; set; }
        public string Prd_season { get; set; }
        public Nullable<float> Hof_score { get; set; }
    }
}
