//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hof_target
    {
        public string Cntr_code { get; set; }
        public string prd_year { get; set; }
        public string prd_season { get; set; }
        public string prd_code { get; set; }
        public string hof_code { get; set; }
        public byte Parcel_Code { get; set; }
        public string vil_code { get; set; }
        public Nullable<float> Hof_Score { get; set; }
        public Nullable<float> plan_area { get; set; }
        public Nullable<double> plan_qty { get; set; }
        public Nullable<System.DateTime> Ent_Date { get; set; }
        public string prd_dummy { get; set; }
    }
}
