//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class kuber_eligiblegrowerLists
    {
        public long id { get; set; }
        public string comp_code { get; set; }
        public string Pono { get; set; }
        public string prd_year { get; set; }
        public string prd_season { get; set; }
        public string ppmsid { get; set; }
        public string gr_code { get; set; }
        public string gr_name { get; set; }
        public string village { get; set; }
        public string taluka { get; set; }
        public string district { get; set; }
        public string state { get; set; }
        public string cntr_code { get; set; }
        public string prd_code { get; set; }
        public string issue_ac { get; set; }
        public string existarea { get; set; }
        public string bank_ac_no { get; set; }
        public string bankname { get; set; }
        public string branch { get; set; }
        public string ifsccode { get; set; }
        public string aadhar { get; set; }
        public string eligibileamt { get; set; }
        public string recom_amt { get; set; }
        public string remarkbyCenterIncharge { get; set; }
        public string center_incharge { get; set; }
        public Nullable<System.DateTime> center_incharge_date { get; set; }
        public string RPM_code { get; set; }
        public string RPM_remark { get; set; }
        public Nullable<System.DateTime> RPM_date { get; set; }
        public string approvedAmt { get; set; }
        public string fileUploadedCount { get; set; }
        public string status { get; set; }
        public string doc_remark_by_CIncharge { get; set; }
        public Nullable<System.DateTime> doc_update_date { get; set; }
        public string finance_usercode { get; set; }
        public string paymentdate { get; set; }
        public string payment_remark { get; set; }
        public string final_amount { get; set; }
    }
}
