//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDO_PaymentTransactionIddetail
    {
        public long id { get; set; }
        public string transactionId { get; set; }
        public Nullable<int> status { get; set; }
        public string farmerid { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
    }
}
