//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MO_Coupan
    {
        public int Tr_id { get; set; }
        public string product { get; set; }
        public string croptype { get; set; }
        public string pkt { get; set; }
        public string discount { get; set; }
        public string coupanCode { get; set; }
        public string userCode { get; set; }
        public Nullable<System.DateTime> reedemDate { get; set; }
        public string year { get; set; }
        public string retailerID { get; set; }
        public string distributorID { get; set; }
        public Nullable<int> productionFlag { get; set; }
    }
}
