//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mo_coupan1
    {
        public int tr_id { get; set; }
        public string product { get; set; }
        public string pkt { get; set; }
        public string discount { get; set; }
        public string coupancode { get; set; }
        public string usercode { get; set; }
        public Nullable<System.DateTime> reedemDate { get; set; }
    }
}
