//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mo_POG
    {
        public int Tr_id { get; set; }
        public string crop { get; set; }
        public string product { get; set; }
        public string pog { get; set; }
        public string sell { get; set; }
        public string sells { get; set; }
        public string returnStk { get; set; }
        public string closeStk { get; set; }
        public string Mweek { get; set; }
        public string usercode { get; set; }
        public Nullable<System.DateTime> Sdate { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string QRCode { get; set; }
    }
}
