//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MO_POGSAP
    {
        public Nullable<int> Rid { get; set; }
        public decimal barcode { get; set; }
        public string matnr { get; set; }
        public string matdesc { get; set; }
        public string batchno { get; set; }
        public Nullable<byte> Qty { get; set; }
        public Nullable<decimal> QTYKG { get; set; }
        public string Flag { get; set; }
    }
}
