//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyTravel_AddPlace
    {
        public int tr_id { get; set; }
        public string usercode { get; set; }
        public string cordinates { get; set; }
        public string geolocation { get; set; }
        public string startdate { get; set; }
        public string startTime { get; set; }
        public string place { get; set; }
        public Nullable<int> flag { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string TFA { get; set; }
    }
}
