//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class National_target
    {
        public string Prd_year { get; set; }
        public string Prd_season { get; set; }
        public string Prd_code { get; set; }
        public Nullable<double> Trg_qty { get; set; }
        public Nullable<double> Sur_def { get; set; }
        public Nullable<System.DateTime> Ent_date { get; set; }
        public string User_Name { get; set; }
        public Nullable<byte> erp_flag { get; set; }
        public Nullable<System.DateTime> erp_date { get; set; }
        public string erp_msg { get; set; }
    }
}
