//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Neworganizer_Master
    {
        public string org_id { get; set; }
        public string org_code { get; set; }
        public string org_name { get; set; }
        public string vil_code { get; set; }
        public string cls_code { get; set; }
        public string talq_code { get; set; }
        public string Dist_code { get; set; }
        public string Stat_code { get; set; }
        public string cntr_code { get; set; }
        public string cntr_abbr { get; set; }
        public string pin_no { get; set; }
        public string mobile_no { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string createby { get; set; }
        public string modifyby { get; set; }
    }
}
