//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewVendorCreation
    {
        public long RowId { get; set; }
        public string VendorType { get; set; }
        public string PurchGroup { get; set; }
        public string Center { get; set; }
        public string State { get; set; }
        public string District { get; set; }
        public string Taluka { get; set; }
        public string Village { get; set; }
        public string VendorName { get; set; }
        public string GuClass { get; set; }
        public string MahClass { get; set; }
        public string NoClass { get; set; }
        public string SoClass { get; set; }
        public string MobileNo { get; set; }
        public string BankName { get; set; }
        public string CreatedBy { get; set; }
        public string ModifyBy { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string RegionCode { get; set; }
        public string aadhar { get; set; }
        public string registerStatus { get; set; }
        public string GSTNo { get; set; }
        public Nullable<long> postal_code { get; set; }
        public string post_name { get; set; }
    }
}
