//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OldSystemPOCreate
    {
        public int row_id { get; set; }
        public string keyName { get; set; }
        public string MasterKey { get; set; }
        public string oldCode { get; set; }
        public string newCode { get; set; }
    }
}
