//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class oranizer_master1
    {
        public string org_type { get; set; }
        public string org_code { get; set; }
        public string org_name { get; set; }
        public string vil_code { get; set; }
        public string cls_code { get; set; }
        public string talq_code { get; set; }
        public string dist_code { get; set; }
        public string state_code { get; set; }
        public string cntr_code { get; set; }
        public string cntr_abbr { get; set; }
    }
}
