//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parcel_Master
    {
        public string hof_code { get; set; }
        public byte Parcel_Code { get; set; }
        public string Parcel_Name { get; set; }
        public Nullable<float> Suit_Area { get; set; }
        public Nullable<float> Not_Suit_Area { get; set; }
        public Nullable<byte> Land_Code { get; set; }
        public Nullable<byte> Irrg_Code { get; set; }
        public Nullable<byte> Rem_Code { get; set; }
        public Nullable<byte> Landol_code { get; set; }
        public Nullable<int> parcel_srno { get; set; }
        public Nullable<System.DateTime> creat_dt { get; set; }
        public Nullable<System.DateTime> Modif_dt { get; set; }
        public string Prd_dummy { get; set; }
    }
}
