//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phy_TagArea1
    {
        public int tr_id { get; set; }
        public string CENTER { get; set; }
        public string PPMS_ID { get; set; }
        public string GROWER_NAME { get; set; }
        public string VILLAGE { get; set; }
        public string HYBRID { get; set; }
        public string IssueArea { get; set; }
        public string TagArea { get; set; }
        public string SATFF_NAME { get; set; }
    }
}
