//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class POCreateDetail
    {
        public long RowId { get; set; }
        public string CompanyCode { get; set; }
        public string Pr_organization { get; set; }
        public string Prd_PlantCode { get; set; }
        public string Prc_plantCode { get; set; }
        public string prc_contract_loc { get; set; }
        public string Material { get; set; }
        public string PaymentTerm { get; set; }
        public string valuatedPO { get; set; }
        public string Cost_center { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    }
}
