//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PPMS_MenuPermission
    {
        public int mid { get; set; }
        public Nullable<int> MenuID { get; set; }
        public string userid { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<bool> AddFlag { get; set; }
        public Nullable<bool> UpdateFlag { get; set; }
        public Nullable<bool> ViewFlag { get; set; }
        public Nullable<bool> RowStatus { get; set; }
        public Nullable<int> createby { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> modifyby { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
