//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Procurement_Price
    {
        public string Cntr_code { get; set; }
        public string prd_year { get; set; }
        public string prd_code { get; set; }
        public Nullable<float> Procure_price { get; set; }
    }
}
