//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Master
    {
        public string Prd_year { get; set; }
        public string Prd_Code { get; set; }
        public string Crop_Code { get; set; }
        public string Prd_Desc { get; set; }
        public string Prd_desc1 { get; set; }
    }
}
