//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgressEntry_CI
    {
        public int gr_id { get; set; }
        public Nullable<int> Rid { get; set; }
        public string prd_year { get; set; }
        public string session { get; set; }
        public string cntrcode { get; set; }
        public string usercode { get; set; }
        public string ReviewBy { get; set; }
        public string product { get; set; }
        public string FS_Dist_AC { get; set; }
        public string Sown_AC { get; set; }
        public string CMR_30_EXT_AC { get; set; }
        public string CMR_30_EST_QTY { get; set; }
        public string CMR_40_EXT_AC { get; set; }
        public string CMR_40_EST_QTY { get; set; }
        public string Ext_area { get; set; }
        public string Ext_gr { get; set; }
        public string crop_stage { get; set; }
        public string esti_yeild { get; set; }
        public string desp_ac { get; set; }
        public string desp_qty { get; set; }
        public string bal_desp_ac { get; set; }
        public string bal_desp_qty { get; set; }
        public string jan1 { get; set; }
        public string jan2 { get; set; }
        public string feb1 { get; set; }
        public string feb2 { get; set; }
        public string mar1 { get; set; }
        public string mar2 { get; set; }
        public string apr1 { get; set; }
        public string apr2 { get; set; }
        public string may1 { get; set; }
        public string may2 { get; set; }
        public string jun1 { get; set; }
        public string jun2 { get; set; }
        public string jul1 { get; set; }
        public string jul2 { get; set; }
        public string aug1 { get; set; }
        public string aug2 { get; set; }
        public string sep1 { get; set; }
        public string sep2 { get; set; }
        public string oct1 { get; set; }
        public string oct2 { get; set; }
        public string nov1 { get; set; }
        public string nov2 { get; set; }
        public string dec1 { get; set; }
        public string dec2 { get; set; }
        public string totalArrival { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<byte> flag { get; set; }
    }
}
