//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisteredDevice
    {
        public string IMEI_No { get; set; }
        public System.DateTime Registration_Date { get; set; }
        public string Staff_ID { get; set; }
        public string MailID { get; set; }
        public Nullable<System.DateTime> Deactivation_Date { get; set; }
        public string Mobile_No { get; set; }
    }
}
