//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region_target
    {
        public string Reg_code { get; set; }
        public string Prd_year { get; set; }
        public string Prd_season { get; set; }
        public string Prd_code { get; set; }
        public Nullable<byte> Reg_rank { get; set; }
        public Nullable<double> Trg_qty { get; set; }
        public string Eval_code { get; set; }
        public string Eval_FYrSn { get; set; }
        public string Eval_SYrSn { get; set; }
        public string Eval_TYrSn { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> Ent_date { get; set; }
        public string User_name { get; set; }
    }
}
