//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource_Master
    {
        public byte Com_no { get; set; }
        public byte Res_Code { get; set; }
        public string Res_Desc { get; set; }
        public string Res_Abbr { get; set; }
    }
}
