//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Saprfc_log
    {
        public string tran_name { get; set; }
        public System.DateTime tran_date { get; set; }
        public Nullable<int> tran_tot { get; set; }
        public Nullable<int> tran_suc { get; set; }
        public Nullable<int> tran_err { get; set; }
    }
}
