//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score_Data
    {
        public string Cntr_code { get; set; }
        public string prd_year { get; set; }
        public string Prd_season { get; set; }
        public string prd_code { get; set; }
        public string gr_code { get; set; }
        public byte Parcel_Code { get; set; }
        public float issue_area { get; set; }
        public double unp_qty { get; set; }
        public double prc_qty { get; set; }
        public float Prd_vity { get; set; }
        public float gr_score { get; set; }
        public string prv_crop { get; set; }
        public string gr_cnt_Catg { get; set; }
        public double gr_trgqty { get; set; }
        public double gr_expyld { get; set; }
        public Nullable<byte> flag { get; set; }
        public string Field1 { get; set; }
        public string Field2 { get; set; }
    }
}
