//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop_crops
    {
        public int tr_id { get; set; }
        public string crp_Type { get; set; }
        public string crp_catagary { get; set; }
        public string status { get; set; }
        public string imgurl { get; set; }
        public string cropgrp { get; set; }
        public Nullable<byte> crp_pri { get; set; }
    }
}
