//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop_cmp_image
    {
        public int tr_id { get; set; }
        public string cmpName { get; set; }
        public string imgUrl { get; set; }
        public string stauts { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> inactiveDate { get; set; }
        public Nullable<int> cmp_pri { get; set; }
    }
}
