//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Depo_Email
    {
        public int tr_id { get; set; }
        public string depo_name { get; set; }
        public string email_id { get; set; }
        public string Depomobile { get; set; }
        public string RBMMobile { get; set; }
    }
}
