//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_New_Village_Master
    {
        public string vil_code { get; set; }
        public string vil_desc { get; set; }
        public string vil_class { get; set; }
        public Nullable<System.DateTime> entrydate { get; set; }
    }
}
