//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop_manufacture_master
    {
        public int cust_id { get; set; }
        public string Firm_name { get; set; }
        public string EmailID { get; set; }
        public string MobileNo { get; set; }
        public string Name { get; set; }
        public string pincode { get; set; }
        public string Cu_State { get; set; }
        public string Cu_dist { get; set; }
        public string Cu_taluka { get; set; }
        public string PAN_no { get; set; }
        public string GST_No { get; set; }
        public string Cu_address { get; set; }
        public string Cu_City { get; set; }
        public string Seedlicense { get; set; }
        public string BankName { get; set; }
        public string AccountNumber { get; set; }
        public string IFSCCode { get; set; }
        public Nullable<int> isProfileUpdate { get; set; }
        public string termsApprove { get; set; }
        public Nullable<System.DateTime> termsApproveDate { get; set; }
        public string alternerNumber { get; set; }
        public string company_website { get; set; }
        public string cmp_email { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
    }
}
