//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop_seedling_request
    {
        public int tr_id { get; set; }
        public string crop_name { get; set; }
        public string varity { get; set; }
        public string retailer_mobile { get; set; }
        public string qty { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> tr_date { get; set; }
        public string ExDate { get; set; }
    }
}
