//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop_discountDetails
    {
        public int tr_id { get; set; }
        public string itemCode { get; set; }
        public string discountAmt { get; set; }
        public string TotalAmt { get; set; }
        public string discountCatagory { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> tr_date { get; set; }
    }
}
