//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_Farmer_Details
    {
        public long gr_code { get; set; }
        public string gr_name { get; set; }
        public string Vil_code { get; set; }
        public string Vil_name { get; set; }
        public string Talq_code { get; set; }
        public string Talq_name { get; set; }
        public string Dist_code { get; set; }
        public string Dist_name { get; set; }
        public string Stat_code { get; set; }
        public string state_name { get; set; }
        public Nullable<byte> flag { get; set; }
    }
}
