//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_parcelmaster
    {
        public string hof_code { get; set; }
        public byte Parcel_Code { get; set; }
        public string Parcel_Name { get; set; }
        public float Suit_Area { get; set; }
        public float Not_Suit_Area { get; set; }
        public byte Land_Code { get; set; }
        public byte Irrg_Code { get; set; }
        public byte Rem_Code { get; set; }
        public byte Landol_code { get; set; }
        public float parcel_srno { get; set; }
    }
}
