//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_hofmaster
    {
        public string hof_Code { get; set; }
        public string hof_name { get; set; }
        public float parcel_srno { get; set; }
        public int Yob_code { get; set; }
        public byte Age_Code { get; set; }
        public byte Edu_Code { get; set; }
        public byte HG_Code { get; set; }
        public byte Mahexpr_Code { get; set; }
        public byte Compexpr_Code { get; set; }
        public byte Labour_Code { get; set; }
        public byte Trac_Code { get; set; }
        public byte Bull_Code { get; set; }
        public byte Cap_Code { get; set; }
    }
}
