//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempData
    {
        public int ImageID { get; set; }
        public string ImageName { get; set; }
        public string ImageContent { get; set; }
        public string tagdata { get; set; }
        public System.DateTime CreatedDt { get; set; }
        public string Updatedby { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
        public bool Active { get; set; }
    }
}
