//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit_Master
    {
        public string Reg_code { get; set; }
        public string Cntr_code { get; set; }
        public string Crop_Code { get; set; }
        public string Prd_Code { get; set; }
        public Nullable<float> Units { get; set; }
    }
}
