//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class upload_sapcmrdata
    {
        public string cntr_code { get; set; }
        public string prd_year { get; set; }
        public string Prd_season { get; set; }
        public string prd_code { get; set; }
        public string ebeln { get; set; }
        public string ebelp { get; set; }
        public string gr_code { get; set; }
        public string charg { get; set; }
        public byte parcel_Code { get; set; }
        public double unp_qty { get; set; }
        public float po_area { get; set; }
        public float issu_area { get; set; }
        public float sown_area { get; set; }
        public float ntsown_area { get; set; }
        public float ext_area { get; set; }
        public float pld_area { get; set; }
        public float rej_area { get; set; }
        public float recd_area { get; set; }
        public float nrecd_area { get; set; }
        public Nullable<System.DateTime> fplant_date { get; set; }
        public Nullable<System.DateTime> mplant_date { get; set; }
        public int f_row { get; set; }
        public int m_row { get; set; }
        public int f_tpp { get; set; }
        public int m_tpp { get; set; }
        public string field1 { get; set; }
        public string field2 { get; set; }
        public string field3 { get; set; }
    }
}
