//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_log
    {
        public string user { get; set; }
        public Nullable<System.DateTime> login { get; set; }
        public Nullable<System.DateTime> logout { get; set; }
        public string cname { get; set; }
        public string comip { get; set; }
    }
}
