//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_authorization
    {
        public byte User_code { get; set; }
        public byte Tran_type_code { get; set; }
        public byte Tran_seq { get; set; }
        public string tran_code { get; set; }
        public string Tran_type_name { get; set; }
        public string Tran_name { get; set; }
        public string User_auth { get; set; }
    }
}
