//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Tran_Auth
    {
        public byte User_code { get; set; }
        public string tran_code { get; set; }
        public string Cntr_code { get; set; }
        public Nullable<System.DateTime> Auth_date { get; set; }
    }
}
