//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Wallet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_Wallet()
        {
            this.User_Wallet_LogInfo = new HashSet<User_Wallet_LogInfo>();
        }
    
        public long Id { get; set; }
        public string UserBalance { get; set; }
        public string user_code { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<byte> Validdays { get; set; }
        public string amt_addedFrom { get; set; }
    
        public virtual Shop_Retailer_UserMaster Shop_Retailer_UserMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Wallet_LogInfo> User_Wallet_LogInfo { get; set; }
    }
}
