//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Master
    {
        public byte User_Code { get; set; }
        public string User_Name { get; set; }
        public string User_Pwd { get; set; }
        public string User_Desg { get; set; }
        public string User_emailid { get; set; }
        public string User_status { get; set; }
    }
}
