//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.DAL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class village_esti_entry
    {
        public int Rid { get; set; }
        public string staff_code { get; set; }
        public string vil_code { get; set; }
        public string Prd_code { get; set; }
        public string estimated_yeild { get; set; }
        public System.DateTime date { get; set; }
    }
}
